### ISSUE TITLE
-sync problem Unable to locate google drive file map for: com.whatsapp

### ISSUE THREAD

**Issue by wootw0rm** [B16f00t/whapa#1]
i have notify
whagdext.py -sync
Unable to locate google drive file map for: com.whatsapp

**Comment by B16f00t** [comment]
Make sure you have entered the phone number associated with the whatsapp account in the celnumber field inside the settings.cfg file.
The number can not contain 00 or +, enter the country code and your phone number.

**Comment by wootw0rm** [comment]
i have other error:

root@kali:~/Tools/whapa# python3 ./whagdext.py -sync
Traceback (most recent call last):
  File "./whagdext.py", line 277, in <module>
    main()
  File "./whagdext.py", line 261, in main
    runMain('sync', 'all', 0)
  File "./whagdext.py", line 208, in runMain
    drives = gDriveFileMap()
  File "./whagdext.py", line 76, in gDriveFileMap
    for result in jres['items']:
KeyError: 'items'

**Comment by B16f00t** [comment]
1. Disable 2FA in your Google Account 
2. Download the latest version of whagdext.py
3. Install the requirements:
       sudo apt-get update
       sudo apt-get install -y python3-pip
       sudo pip3 install pyportify
4. Configure:
        Edit only the values of the./cfg/settings.cfg file
	[auth]
	gmail = alias@gmail.com
	passw = yourpassword
	devid = Device ID (optional, if specified get more information)
	celnumbr = BackupPhoneNumber (ex. 3466666666666, no + or 00)
5. Use on a terminal: python3 whagdext.py -list.
     If you request it, log in to your browser and then click here, https://accounts.google.com/DisplayUnlockCaptcha.
6. If it lists all the files in the account then try the '-sync' flag.
7. Try another account if it's possible to see if the error continues.

**Comment by wootw0rm** [comment]
root@kali:~/Tools/whapa# python3 ./whagdext.py -sync
Traceback (most recent call last):
  File "./whagdext.py", line 278, in <module>
    distutils.dir_util.mkpath("./logs")
NameError: name 'distutils' is not defined

**Comment by B16f00t** [comment]
I have released a new tool, whagodri.py

**Comment by svsagar85** [comment]
> 1. Disable 2FA in your Google Account
> 2. Download the latest version of whagdext.py
> 3. Install the requirements
> 4. Configure:
>    Edit only the values of the./cfg/settings.cfg file
>    [auth]
>    gmail = [alias@gmail.com](mailto:alias@gmail.com)
>    passw = yourpassword
>    devid = Device ID (optional, if specified get more information)
>    celnumbr = BackupPhoneNumber (ex. 3466666666666, no + or 00)
> 5. Use on a terminal: python3 whagdext.py -list.
>    If you request it, log in to your browser and then click here, https://accounts.google.com/DisplayUnlockCaptcha.
> 6. If it lists all the files in the account then try the '-sync' flag.
> 7. Try another account if it's possible to see if the error continues.

@B16f00t thank you!!...this worked for me!

**Comment by prashantvermacs18** [comment]
i have same problem ..pls help

**Comment by hndrk92** [comment]
Hey, here ist the solution for this problem. Use this tool for the Download and it works, I tested it yesterday. Pls look first into the readme for questions! 

https://github.com/B16f00t/whapa

**Comment by Lootierrez** [comment]
@wootw0rm did you solve it? I have the same problem and I don't know what else to do.

**Comment by mageshkandan** [comment]
thanks @hndrk92 it worked for me. For everyone struggling with unable to locate google drive error. Please ignore that software and download the one which @hndrk92 mentioned. Read the readme file before working on. It working perfectly for me... any query please contact me twitter @mageshmagi

**Comment by laserbu** [comment]
Hi @hndrk92 that also gives me the following errors:

Collecting pycryptodome
  Using cached https://files.pythonhosted.org/packages/b6/41/d3749c0caa860041eb6b0832c7087253d59cb5af8bb303a8d4b6daa74014/pycryptodome-3.9.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\lype\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LyPe\\AppData\\Local\\Temp\\pip-install-kscsqi4m\\pycryptodome\\setup.py'"'"'; __file__='"'"'C:\\Users\\LyPe\\AppData\\Local\\Temp\\pip-install-kscsqi4m\\pycryptodome\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\LyPe\AppData\Local\Temp\pip-install-kscsqi4m\pycryptodome\pip-egg-info'
         cwd: C:\Users\LyPe\AppData\Local\Temp\pip-install-kscsqi4m\pycryptodome\
    Complete output (31 lines):
    Traceback (most recent call last):
      File "c:\users\lype\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LyPe\AppData\Local\Temp\pip-install-kscsqi4m\pycryptodome\setup.py", line 448, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\LyPe\AppData\Local\Temp\pip-install-kscsqi4m\pycryptodome\compiler_opt.py", line 304, in set_compiler_options
        clang = compiler_is_clang()
      File "C:\Users\LyPe\AppData\Local\Temp\pip-install-kscsqi4m\pycryptodome\compiler_opt.py", line 239, in compiler_is_clang
        return test_compilation(source, msg="clang")
      File "C:\Users\LyPe\AppData\Local\Temp\pip-install-kscsqi4m\pycryptodome\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
      File "c:\users\lype\appdata\local\programs\python\python38-32\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\users\lype\appdata\local\programs\python\python38-32\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\lype\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\lype\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\users\lype\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\users\lype\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    Testing support for clang
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by hndrk92** [comment]
Hi @laserbu, did you have fully installed python?

**Comment by laserbu** [comment]
it works! thanks

**Comment by hndrk92** [comment]
I do my best, you're welcome @laserbu👍

**Comment by ronitu22** [comment]
Hi @hndrk92 ,  can you help me with this massage ? i have 3.7.5 version and the requirements are installed. who can i make it work ? 

`Traceback (most recent call last):
  File "C:\Users\Roni\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 788, in get
    value = d[option]
  File "C:\Users\Roni\AppData\Local\Programs\Python\Python37-32\lib\collections\__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Users\Roni\AppData\Local\Programs\Python\Python37-32\lib\collections\__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: 'devid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\libs\whagodri.py", line 58, in getConfigs
    devid = config.get('auth', 'devid')
  File "C:\Users\Roni\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'devid' in section: 'auth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\libs\whagodri.py", line 258, in <module>
    getConfigs()
  File ".\libs\whagodri.py", line 65, in getConfigs
    except(ConfigParser.NoSectionError, ConfigParser.NoOptionError):
AttributeError: type object 'ConfigParser' has no attribute 'NoSectionError'`

**Comment by hndrk92** [comment]
Hi @ronitu22, du didn't install the python right or the settings are wrong. Go back to the start and deinstall pyhton! Install it fresh, install the required contents for pyhton and then open the tool. You do the same in the programm, install the required contents over the button in the header and fill out the settings!

In this video you will see, how pyhton get install right, look at 5 minutes and watch till the end. I hope it helped 👍

**Comment by ronitu22** [comment]
> Hi @ronitu22, du didn't install the python right or the settings are wrong. Go back to the start and deinstall pyhton! Install it fresh, install the required contents for pyhton and then open the tool. You do the same in the programm, install the required contents over the button in the header and fill out the settings!
> 
> In this video you will see, how pyhton get install right, look at 5 minutes and watch till the end. I hope it helped 👍

thank you a lot @hndrk92! it works!

**Comment by laserbu** [comment]
Hello again @hndrk92:

By any chance whapa master can extract the key to decrypt whatsapp messages? I have tried with DB Extractor and Whatsdump and nothing. Could you please help me?
 Maybe also @B16f00t can help me.
Thanks!

**Comment by hndrk92** [comment]
Hi @laserbu, you cannot decrypt whatsapp massages at this moment. There no solutions or methods for this problem! The cryptkey version is to high to crack it. So sorry, i can't help you 😔

**Comment by laserbu** [comment]
Hi @hndrk92,
I have the phone, but I need a key extractor. I haven't found a working app
to extract it.
Regards,

**Comment by B16f00t** [comment]
to get the key you must root your phone or set up a virtual machine with
your Gogle Drive account and your phone such as genymotion and copy the
data key / com.whatsapp / files / key

**Comment by laserbu** [comment]
I think that's too complicated for me, but I'll try. Thanks a lot @b16f00t

**Comment by demoo1403** [comment]
hi @hndrk92 
please help me solve the same proplem
Traceback (most recent call last):
File ".\libs\whagodri.py", line 258, in 
getConfigs()
File ".\libs\whagodri.py", line 65, in getConfigs
except(ConfigParser.NoSectionError, ConfigParser.NoOptionError):
AttributeError: type object 'ConfigParser' has no attribute 'NoSectionError'`

**Comment by kduramos** [comment]
Hi @hndrk92   please can you help me?
When i try to use Whagodry  i receive this messages:

[e] Error:  Requested entity was not found.
[e] Unable to locate google drive file map for: com.whatsapp <Response [404]>
[i] Generating threads...
Traceback (most recent call last):
  File ".\libs\whagodri.py", line 314, in <module>
    getMultipleFiles(drives, bearer, filter)
  File ".\libs\whagodri.py", line 159, in getMultipleFiles
    print("[+] Backup name : {}".format(drives["name"]))

I put allinformations right and i try in two differents accounts and as the same thing

**Comment by danieldivantoquemolina** [comment]
Estoy Presentando el siguiente error alguien podría ayudarme:

[e] Error:  Backup API not enabled
[e] Unable to locate google drive file map for: com.whatsapp <Response [403]>
[i] Generating threads...
Traceback (most recent call last):
  File ".\libs\whagodri.py", line 314, in <module>
    getMultipleFiles(drives, bearer, filter)
  File ".\libs\whagodri.py", line 159, in getMultipleFiles
    print("[+] Backup name : {}".format(drives["name"]))
KeyError: 'name'
