### ISSUE TITLE
Unable to locate google drive file map for: com.whatsapp

### ISSUE THREAD

**Issue by gabrielPardini** [B16f00t/whapa#10]
Hi!

I received this error message when trying to run the script.

Every configuration seems to be in order.

O tried usng postman to run the same request that your function makes to get the file map from google drive. 
I dont get any errors from the google api, but the items array comes empty

I already checked if the backup is present in my google drive for the same avccount and it is there.

any thoughts?

**Comment by B16f00t** [comment]
Follow this:
1. Disable 2FA in your Google Account
2. Download the latest version of whagodri.py
3. Install the requirements
Configure:
Edit only the values of the./cfg/settings.cfg file
[auth]
gmail = alias@gmail.com
passw = yourpassword
devid = Device ID (optional, if specified get more information)
celnumbr = BackupPhoneNumber (ex. 3466666666666, no + or 00)
4. Use on a terminal: python3 whagdext.py -list.
If you request it, log in to your browser and then click here, https://accounts.google.com/DisplayUnlockCaptcha.
If it lists all the files in the account then try the '-sync' flag.
Try another account if it's possible to see if the error continues.

**Comment by gabrielPardini** [comment]
Everything is configured like that.
Ive download the most recent whagodri files.
Also im using python 2.7 since when i tryed using with python 3 i got sintax errors in the comments for the banner

**Comment by gabrielPardini** [comment]
Ill test on a differnt account to see what happens

**Comment by B16f00t** [comment]
I just tested my account and it works perfectly, see if the problem is with that account, and let me know.
![captura de pantalla de 2019-02-07 16-39-08](https://user-images.githubusercontent.com/33256758/52422770-06bf4d80-2af7-11e9-9fb7-9db754f52fb0.png)

**Comment by gabrielPardini** [comment]
Got it. There was a problem with one of my requests, but probably my fault for fiddling with it.

Just downloaded my DB.

Now a need list of all the contacts in my db, wich is the most apropiate opton in whapa?

**Comment by gabrielPardini** [comment]
im not sure about the key needed for the decrytion.

**Comment by B16f00t** [comment]
To decrypt the database you will have to have root access to your phone and pull the key file, located at /data/data/com.whatsapp/files/key.
The whatsapp database is not stored in msgstore.db, but the wa.db database inside the phone's internal whatsapp folder.
With whapa you can only extract the conversations held with users, statuses, images, etc ...

**Comment by gabrielPardini** [comment]
nice.

thks

**Comment by cm162193** [comment]
gabrielPardini, in which request was the problem? Because im getting the same error
