### ISSUE TITLE
very slow database parser

### ISSUE THREAD

**Issue by bimarifin** [B16f00t/whapa#101]
Hi, 

it takes 4 days for me to parse TEXT only from Parse Database menu, 

1.158 items chat / html reports.

thats crazy..

**Comment by B16f00t** [comment]
As specified in the README file, whapa runs much faster under Llinux than under windows.
Could you please specify your operating system?
Also I would like you to test without applying filters,
I noticed some time ago that applying them increased a lot the parsing time.

**Comment by bimarifin** [comment]
will check on Linux, thanks
