### ISSUE TITLE
wa.db not exported; wa_contacts empty 

### ISSUE THREAD

**Issue by biejay** [B16f00t/whapa#102]
Hi, i **was able to decrypt my msgstore.db.crypt14** file but i **only got the msgstore.db**. 
I **expected to get the wa.db** also.
I got the wa.db via a **different software** but from there, the **wa_contacts table in wa.db is empty**, so i can't match the contact names.

Is this an known issue?

**Comment by B16f00t** [comment]
whapa gets the names from the wa.db database, if the database does not exist or is empty, no names will be displayed.
To get these files in many cases you must be root, or extract by other methods.
Google Drive does not store such a database.
