### ISSUE TITLE
Never seen this error before: Error=ServerError

### ISSUE THREAD

**Issue by Mystefyer** [B16f00t/whapa#104]
Hi,

Today I got this:

 Requesting Auth for Google....
Granted

Getting Token from Google....
Failed

Error=ServerError

Tested it with my backup phone and google account and that one works fine. Tried using https://accounts.google.com/DisplayUnlockCaptcha but that did not help. Any ideas what the problem could be?

**Comment by Mystefyer** [comment]
Just checked again, its working now....odd

**Comment by B16f00t** [comment]
the error indicated a server error, I imagine it was something temporary
