### ISSUE TITLE
Error -3 while decompressing data incorrect header check

### ISSUE THREAD

**Issue by gabrielPardini** [B16f00t/whapa#11]
Hi there.

I started to get this error:

Error -3 while decompressing data incorrect header check
while trying to decript the database extracted.
I changed the device in which whatsapp is installed for this number, but read that it doesnt matter for the key that i've retrived using root access.

Any thougths?

**Comment by B16f00t** [comment]
the problem is that you have generated a new key in the new device, a method to generate it would be to copy the encrypted database in the sd, install WhatsApp and recover that copy, this would generate the same encryption key, and you could decipher with whapa
