### ISSUE TITLE
Error=NeedsBrowser

### ISSUE THREAD

**Issue by cRaZy-2012** [B16f00t/whapa#110]
Getting Error=NeedsBrowser. Tried with  different account, 2FA turned off and on, App security key, Display Captcha, nothing worked.

**Comment by Pinguino71** [comment]
I had the same problem. Try to upgrade modules with the requeriment.txt
pip install --upgrade -r ./doc/requirements.txt

I did and started to work again

**Comment by B16f00t** [comment]
Same Issue #106
