### ISSUE TITLE
Export messages 

### ISSUE THREAD

**Issue by gnu-like** [B16f00t/whapa#112]
**OS Ubuntu** 

**V 1.44** There is no export option. just shows in terminal I wanna save messages such as pdf or csv format.

**Comment by B16f00t** [comment]
The program generates an html file, which you can then print as a pdf file if you have the appropriate software installed.

**Comment by gnu-like** [comment]
> The program generates an html file, which you can then print as a pdf file if you have the appropriate software installed.

Yes.that's right .
