### ISSUE TITLE
can you update the new crypt 14 offset

### ISSUE THREAD

**Issue by unknowen700** [B16f00t/whapa#113]
can you update the new crypt 14 offset 
whatsapp new crypt 14 db has been changed again ?

**Comment by augustoraphael** [comment]
As mentioned in the previous isssue (link below), I think it has changed again. I got success descrypting my database just after change my whacipher.py file in lines 79 and 80 to the following:

data = db_data[191:]
iv = db_data[67:83]

https://github.com/B16f00t/whapa/issues/96#issuecomment-850997115

The above suggestion must be considered in the solution.

**Comment by unknowen700** [comment]
how did you know the change 
i mean how can i get new offset if WhatsApp change it agien

**Comment by unknowen700** [comment]
th you it work but how can i know the change if any update happen

**Comment by augustoraphael** [comment]
Actualy, I don't know about that as well. I only followed the instructions of @ElDavoo in the previous post. Maybe he can help us about your question.

**Comment by ElDavoo** [comment]
I made a small bruteforcer, changing a python decryptor, that tried out all possible values. Gave it some hours and called it a day.
There are probably better ways

**Comment by B16f00t** [comment]
I'm still not sure what the correct values are and if they change based on something, if anyone has the latest good values I'll modify them in the script.

**Comment by selvania** [comment]
I can confirm that the values seem to be no longer valid. Also, we were forced to run the app on windows, it seems mac's don't accept the crypt14 filetype. I looked through the code but couldn't find the cause....

**Comment by leosol** [comment]
Just worked for me with version 2.21.12.21 (tested with w4b and regular whatsapp).
I think that it would be very nice to have this in trunk: 

```
data = db_data[191:]
iv = db_data[67:83]
```

**Comment by B16f00t** [comment]
Someone try the new values?

**Comment by ElDavoo** [comment]
I deleted it. Lmao

The new values I wrote should work.

**Comment by aldosimon** [comment]
> 
> 
> As mentioned in the previous isssue (link below), I think it has changed again. I got success descrypting my database just after change my whacipher.py file in lines 79 and 80 to the following:
> 
> data = db_data[191:]
> iv = db_data[67:83]
> 
> [#96 (comment)](https://github.com/B16f00t/whapa/issues/96#issuecomment-850997115)
> 
> The above suggestion must be considered in the solution.

thank you...worked like a charm!
