### ISSUE TITLE
Unable to retrive data from Whatsapp

### ISSUE THREAD

**Issue by maamirh** [B16f00t/whapa#116]
I am facing an issue that I entered the correct username and password but click on the link GoogleCaptachaUnlock too but getting the same error message again and again whereas two-factor security is also not activated.

![image](https://user-images.githubusercontent.com/46965638/123384243-96250880-d5ad-11eb-8559-1f9f4eaf6ca5.png)

**Comment by TITAN6146** [comment]
Estamos todos con el mismo problema

**Comment by B16f00t** [comment]
Mañana saco la versión con el problema arreglado
I’ll release a new version tomorrow with the fix

**Comment by B16f00t** [comment]
#106
