### ISSUE TITLE
Carving of whatsapp key

### ISSUE THREAD

**Issue by leosol** [B16f00t/whapa#117]
Guys, you have a very nice tool here. Would you be interested in something that could help find "lost" keys (carved ones)?
Take a look if you find this usefull: https://github.com/leosol/whatsapp-key-carver
I could work on a PR for this...

**Comment by B16f00t** [comment]
It's interesting, have you ever taken a key that could be used to decrypt a database?

**Comment by B16f00t** [comment]
I understand that if you have an image with ufed you can navigate the directory tree and get the key of the whatsapp path.  Another problem is that by default the backups are mostly encrypted.  but I see the project interesting to incorporate within the suite
