### ISSUE TITLE
OSError: Cannot load native module 'Cryptodome.Hash._MD5': Trying '_MD5.pyd': [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by necromancer99999** [B16f00t/whapa#12]
When i try to run whagodri.py, I get the following issue:

Traceback (most recent call last):
  File "whagodri.py", line 4, in <module>
    from gpsoauth import google
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 38, in
< module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 44, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 43, in <module>
    from Cryptodome.Hash import MD5, SHA1
  File "C:\Python27\lib\site-packages\Cryptodome\Hash\MD5.py", line 47, in <module>
    """)
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 258, in
 load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attemp
ts)))
OSError: Cannot load native module 'Cryptodome.Hash._MD5': Trying '_MD5.pyd': [E
rror 193] %1 is not a valid Win32 application

Is there anyone get same issue ? How do i repair this ?
Thanks

**Comment by B16f00t** [comment]
Install requirements

**Comment by necromancer99999** [comment]
I was installed all requirements. But still have error. Here is the messege

==========START OF INSTALL REQUIREMENTS=======

D:\newst\bigf00t>pip2 install pycryptodome
Requirement already satisfied: pycryptodome in c:\python27\lib\site-packages (3.
6.1)
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

D:\newst\bigf00t>pip2 install colorama
Requirement already satisfied: colorama in c:\python27\lib\site-packages (0.3.9)

You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

D:\newst\bigf00t>pip2 install BeautifulSoup
Requirement already satisfied: BeautifulSoup in c:\python27\lib\site-packages (3
.2.1)
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

D:\newst\bigf00t>pip2 install configparser
Requirement already satisfied: configparser in c:\python27\lib\site-packages (3.
5.0)
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

D:\newst\bigf00t>pip2 install gpsoauth
Requirement already satisfied: gpsoauth in c:\python27\lib\site-packages (0.4.1)

Requirement already satisfied: pycryptodomex>=3.0 in c:\python27\lib\site-packag
es (from gpsoauth) (3.6.1)
Requirement already satisfied: requests in c:\python27\lib\site-packages (from g
psoauth) (2.19.0)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in c:\python27\lib\site-pac
kages (from requests->gpsoauth) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-pac
kages (from requests->gpsoauth) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packag
es (from requests->gpsoauth) (2018.4.16)
Requirement already satisfied: idna<2.8,>=2.5 in c:\python27\lib\site-packages (
from requests->gpsoauth) (2.7)
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.
========== END OF INSTALL REQUIREMENTS=======

========== START OF ERROR =======
D:\newst\bigf00t>py -2 whagodri.py -i
Traceback (most recent call last):
  File "whagodri.py", line 4, in <module>
    from gpsoauth import google
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line 38, in
<module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 44, in <modu
le>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 43, in <modu
le>
    from Cryptodome.Hash import MD5, SHA1
  File "C:\Python27\lib\site-packages\Cryptodome\Hash\MD5.py", line 47, in <modu
le>
    """)
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line 258, in
 load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attemp
ts)))
OSError: Cannot load native module 'Cryptodome.Hash._MD5': Trying '_MD5.pyd': [E
rror 193] %1 is not a valid Win32 application

==========END OF ERROR =======


>

**Comment by necromancer99999** [comment]
This issue is solved.
I was uninstall all version python, and installed new version 27 and 3 with with 32bit installer and it works perfectly
Thanks b16foot :)
