### ISSUE TITLE
Error -3 while decompressing data: incorrect header check

### ISSUE THREAD

**Issue by josemilagre** [B16f00t/whapa#120]
Hello

When a try decrypt onde .db.crypt12 with the extract key, i got this message:

[i] Starting to decrypt...
[e] An error has ocurred decrypting 'msgstore.db.crypt12' -  Error -3 while decompressing data: incorrect header check

Whats happen here?

**Comment by B16f00t** [comment]
The current version only supports crypt14, I will have to continue support for crypt12 for a while.
You can try an older version of whapa or wait for me to upgrade to a newer one.

**Comment by B16f00t** [comment]
The latest version support Crypt12 back

**Comment by josemilagre** [comment]
Thank you, querer can i download old version?

Em ter, 29 de jun de 2021 15:56, Ivan Moreno ***@***.***>
escreveu:

**Comment by B16f00t** [comment]
The latest version of whapa supports crypt12 and crypt14, if you get an error, it is because the key you are using is not valid for that backup.
