### ISSUE TITLE
Can whacipher.py decrypt media files?

### ISSUE THREAD

**Issue by beckietech** [B16f00t/whapa#122]
I've followed instructions and the dbs encrypted with crypt14 has been solved! Thank you!

Im wondering if this tool can be used for image decrypt, too?

**Comment by B16f00t** [comment]
What kind of image?

**Comment by beckietech** [comment]
like video/pictures/voice..etc. just wondering how it can be done decrypted

**Comment by B16f00t** [comment]
Media are not encrypted in google drive, only chats are encrypted.

**Comment by beckietech** [comment]
okay
