### ISSUE TITLE
cannot 

### ISSUE THREAD

**Issue by formone98127** [B16f00t/whapa#123]
When using the command line directly to parse msgstore.db, it occured an error: An error occurred connecting to the database name 'company' is not defined

Command line used: python3 ~/whapa/libs/whapa.py -m "/home/user/WADB/msgstore.db" -wa "/home/user/whapa/wa.db" -a -tt -r EN -o /home/user/whapa/report

**Comment by B16f00t** [comment]
The problem is that the tool takes this default value './cfg/settings.cfg', to solve this in the next update, I will put an argument to choose the path of the settings.cfg file or to capture the directory path where whapa is located

**Comment by formone98127** [comment]
lots of thanks!

**Comment by B16f00t** [comment]
Fixed in new version 1.52
