### ISSUE TITLE
KeyError: 'files'

### ISSUE THREAD

**Issue by dhiazulfa** [B16f00t/whapa#124]
Traceback (most recent call last):
  File ".\libs\whagodri.py", line 531, in <module>
    for file in wa_backup.backup_files(backup):
  File ".\libs\whagodri.py", line 238, in list_path
    for item in page[last_component]:
KeyError: 'files'

What can i do with this problem?

**Comment by dhiazulfa** [comment]
Yes i have the updated requirements and i am using python 3.8. Granted show in the login too

**Comment by B16f00t** [comment]
Join the telegram group to try to solve the problem.
