### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by HokeBAr** [B16f00t/whapa#126]
[e] An error has ocurred decrypting 'C:\Users\Users\Desktop\msgstore.db.crypt14' -  Error -3 while decompressing data: incorrect header check

**Comment by B16f00t** [comment]
You have a not valid key for that backup or you have a different offset  #96

**Comment by HokeBAr** [comment]
i have a valid 158 byte key of that exact data base. i double checked everything. But still the same
