### ISSUE TITLE
The 'settings.cfg' file is missing or corrupt!

### ISSUE THREAD

**Issue by floviolleau** [B16f00t/whapa#130]
Hi,

Thanks for your great tool.

I want to have an HTML view of all my messages with media files included like with this great tool: https://github.com/GjjvdBurg/signal2html.

I successfully downloaded from Google Drive by using WhaGoDri. Because I'm rooted, I was able to get my cipher and wa.db from my Android.
I successfully decrypted my msgstore db by using WhaCipher.
Now I'm trying to generate an archive chat list and I have an issue when using WhaPa.

I click on that button:
![image](https://user-images.githubusercontent.com/5442973/127067379-21d9a618-ff92-4ccf-99e1-9c6ba5a48165.png)

Cli ran
```
python3 /home/test/whatsapp-extractor/libs/whapa.py -i 3 -wa /home/test/whatsapp-extractor/my-backup/files/Databases/msgstore.db /home/test/whatsapp-extractor/my-backup/files/Databases/wa.db -r EN
```

Result
```
     __      __.__          __________         
    /  \    /  \  |__ _____ \______   \_____   
    \   \/\/   /  |  \\__  \ |     ___/\__  \  
     \        /|   Y  \/ __ \|    |     / __ \_
      \__/\  / |___|  (____  /____|    (____  /
           \/       \/     \/               \/ 
    ------------- Whatsapp Parser -------------
    
wa.db connected
msgstore.db connected

The 'settings.cfg' file is missing or corrupt!
Actives chat list
[...]
```
I don't understand why this file is missing because when I click on the setting button from the app, it opens and I can edit it.
 
For  info, I'm on Linux:
`Linux linux-laptop 5.8.0-59-generic #66-Ubuntu SMP Thu Jun 17 00:46:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```
I installed the app under a virtual env python3

Thanks a lot!

**Comment by B16f00t** [comment]
It may be a bug of the last update that worked with partial paths and now they are full ones, 
I will check it and let you know.

**Comment by B16f00t** [comment]
Give a try the latest version 1.55

**Comment by floviolleau** [comment]
Works very fine.

Thanks for the quick fix.

Take care

**Comment by Aridetta** [comment]
Shows this Error:

$ python whapa-gui.py
Traceback (most recent call last):
  File "whapa-gui.py", line 1444, in <module>
    with open(cfg_file, 'w') as cfg:
FileNotFoundError: [Errno 2] No such file or directory: '\\cygdrive\\c\\Users\\Lavern\\Downloads\\Master\\whapa-master\\cfg\\settings.cfg'

How do I fix it?

**Comment by B16f00t** [comment]
Tell me your Os and python version

**Comment by Aridetta** [comment]
OS: Windows 10
Python Version: 3.8.10

**Comment by Ibe09** [comment]
me aparece la carpeta sin el settings.cfg, como lo obtengo? espero respuesta, gracias

**Comment by floviolleau** [comment]
> me aparece la carpeta sin el settings.cfg, como lo obtengo? espero respuesta, gracias

Hi,

If you want help from the community, please use English ;)

Thanks

**Comment by Ibe09** [comment]
> > me aparece la carpeta sin el settings.cfg, como lo obtengo? espero respuesta, gracias
> 
> Hola,
> 
> Si desea ayuda de la comunidad, utilice el inglés;)
> 
> Gracias

ok, could you tell me how to get the file please

**Comment by floviolleau** [comment]
Hi,

I don't understand what you mean.
You don't "get" the file. It is part of the repo in cfg folder.

**Comment by B16f00t** [comment]
I deleted the setting file because the program generated it at startup, so that there are no problems I have included it again.
