### ISSUE TITLE
Whagodri - Error in the download with two backups in the same account

### ISSUE THREAD

**Issue by Isaacg001** [B16f00t/whapa#132]
It works well giving the info of he account and all the files but when I start to download it says "Backup (number) omitted"

**Comment by TehBotolSosro** [comment]
same issue with my other account that have 3 number in whatsapp
it can list the file fine but when downloading 

`i] Searching...

Requesting Google access...
Granted

Requesting authentication for Google Drive...
Granted


[i] Backup phonenumber1 omitted

[i] Backup phonenumber2 omitted

[i] Backup phonenumber3 omitted`

**Comment by TehBotolSosro** [comment]
also whapa always hangs when downloading backupnumber2 after it download backupnumber1 for me,
so what i do is change the cfg to backupnumber2 only then retry again

**Comment by Alcazer** [comment]
Can you try the latest version?

**Comment by B16f00t** [comment]
Fixed in the latest version
