### ISSUE TITLE
Is it possible to Update the google drive backup file with the file I want.

### ISSUE THREAD

**Issue by Lavish883** [B16f00t/whapa#137]
My messages got deleted because I got a new phone and new phone didn't restore my message instead it backuped the new messages which was nothing resulting in my messages getting deleted from google drive. But I do have my old messages msgstore.data.crypt14 file. So I was thinking if I can inject that file to google drive.

**Comment by B16f00t** [comment]
You can restore your backup in an android virtual machine and then upload it to google drive.

**Comment by Lavish883** [comment]
I have no clue how I would do that can you please give me a little more specific details.

**Comment by B16f00t** [comment]
Sorry, you can find information about this on the internet here let's stick to application issues.
