### ISSUE TITLE
Incorrect merging

### ISSUE THREAD

**Issue by p4r4d0x86** [B16f00t/whapa#14]
Hello Ivan,

Thank you for your scripts :)

I took a look into your code and I am pretty sure the way of merging message is not working correctly in some cases since "_id" restart from the beginning on every new phone/backup.
It is a good check to avoid duplicating message but not merge two backups from the same number coming from two phones used successively without importing the previous backup.

Give a check here to see:
https://github.com/namnoops/merjapp/blob/649b95948fa547552b280ca90b280ae4aa6987da/src/com/merjapp/Merge.java#L215-L219

Kind regards,
Nico

**Comment by B16f00t** [comment]
whamerge Updated. The script only works with databases that have not been restored.
