### ISSUE TITLE
Decrypt Error

### ISSUE THREAD

**Issue by cansoykaraman** [B16f00t/whapa#140]
Hi
I have crypt14 file and key file.
With these files, the decryption process is successfully completed and the database file is created. 
The created database file can be read easily.
I encrypt this database file again with the same key file and the same crypt14 file.
Encryption also succeeds and cryt14 file is created.
But when I try to decrypt this encrypted file with the same key file, the process goes up to 99 percent and fails. 
Also, when I send the encrypted file to the phone again, the restore process fails. 
Can we find a solution?

**Comment by cansoykaraman** [comment]
So which version of WhatsApp should I use to get the crypto 12 backup file?

**Comment by B16f00t** [comment]
The latest version support crypt14
