### ISSUE TITLE
Downloading partial backup from Google Drive

### ISSUE THREAD

**Issue by guyzyl** [B16f00t/whapa#143]
I reset my phone and discovered after that the Google Drive backup did not complete, and is only partial.
Any idea on how I can download the partial file?
I'm receiving the following error message: 
`Unsupported alt type \\"media\\" for non byte stream request.`

**Comment by B16f00t** [comment]
With Wagodri is not possible.

**Comment by guyzyl** [comment]
Ok, thanks the reply.
