### ISSUE TITLE
"SizeBytes" error

### ISSUE THREAD

**Issue by sebastianberrio** [B16f00t/whapa#144]
I am using the last version of whapa and I get this error when using wagodri

Requesting authentication for Google Drive...
Granted

Traceback (most recent call last):
  File "C:\Users\xxxxxxx\Desktop\whapa-master\libs\whagodri.py", line 444, in <module>
    filter_file[file["name"]] = file["sizeBytes"]
KeyError: 'sizeBytes'

**Comment by B16f00t** [comment]
Maybe a bad backup. Try to set up the config file with your phone and Android ID.
