### ISSUE TITLE
Error: no such table: chat_list

### ISSUE THREAD

**Issue by jorgeortizfuentes** [B16f00t/whapa#145]
Hello! WhaPa gives me the following error.

Error: no such table: chat_list

I have read in some places that the files may be corrupted. I passed my files using adb pull. 

What could have happened?

**Comment by jorgeortizfuentes** [comment]
I was checking the database and discovered that chat_list no longer exists. I don't know if it was renamed or deleted.

**Comment by Whinegum** [comment]
Seems like the database has been renamed. The developers of "whatsapp viewer" have already fixed it:
https://github.com/andreas-mausch/whatsapp-viewer/issues/127#issuecomment-900255460

**Comment by jorgeortizfuentes** [comment]
Thanks! I solved it by changing the table and column name in the Python code.

**Comment by B16f00t** [comment]
Ok thanks I'll review the tables

**Comment by tupini07** [comment]
This issue can probably be closed since #148 was merged.

**Comment by B16f00t** [comment]
Fixed in v1.57, Thanks to @tupini07
