### ISSUE TITLE
Modify database file

### ISSUE THREAD

**Issue by T-vK** [B16f00t/whapa#15]
Hey, great project! Is there an easy way to re-encrypt a decrypted database. For instance if I decrypted the database and replaced all swear words with "****" in all messages, how could I get it back into the format that WhatsApp itself would understand?

From what I understand this is the function responsible for decrypting everything:

``` Python
def decrypt(db_file, key_file):
    """ Function decrypt Crypt12 Database """
    try:
        with open(key_file, "rb") as fh:
            key_data = fh.read()

        key = key_data[126:]
        with open(db_file, "rb") as fh:
            db_data = fh.read()

        iv = db_data[51:67]
        aes = AES.new(key, mode=AES.MODE_GCM, nonce=iv)
        with open("msgstore.db", "wb") as fh:
            fh.write(zlib.decompress(aes.decrypt(db_data[67:-20])))

        print db_file + " decrypted, msgstore.db created."
    except Exception as e:
print "An error has ocurred decrypting the Database:", e
```

But I don't fully understand whats happening here. It looks like you would need `msgstore.db`, `key_data[126:]` as well as  `db_data[0:51]` (whatever that is), `db_data[51:67]` (iv / nonce param for aes) and `db_data[-20:]` (whatever that is) from a encrypted db to encrypt a decrypted `msgstore.db`.

Am I correct so far? Can I just copy `db_data[0:51]`,  `db_data[51:67]` and `db_data[-20:]` from an original encrypted database or are they some sort of checksums that I have to calculate? If so, can you show me how?

This is what I would imagine it to look like:

```
def encrypt(msgstore_db_file, key_file, db_file_to_use_as_reference):
    """ Function encrypt msgstore Database """
    try:
        with open(key_file, "rb") as fh:
            key_data = fh.read()

        key = key_data[126:]

        with open(msgstore_db_file, "rb") as fh:
            msgstore_data = fh.read()

        with open(db_file_to_use_as_reference, "rb") as fh:
            ref_db_data = fh.read()

        header = ref_db_data[0:51]
        iv = ref_db_data[51:67]
        footer = ref_db_data[-20:]

        aes = AES.new(key, mode=AES.MODE_GCM, nonce=iv)
        with open("wa.db", "wb") as fh:
            fh.write(header + iv + aes.encrypt(zlib.compress(msgstore_data)) + footer)

        print db_file + " encrypted, wa.db created."
    except Exception as e:
print "An error has ocurred encrypting the Database:", e
```

I'd really appreciate it if you could help me figure this out.

**Comment by B16f00t** [comment]
I am going to update the project soon.
This a new feature, and this is the function.

def encrypt(db_file, key_file, db_cript):
    """ Function encrypt msgstore Database """
    try:
        with open(key_file, "rb") as fh:
            key_data = fh.read()

        key = key_data[126:]

        with open(db_cript, "rb") as fh:
            db_cript_data = fh.read()

        header = db_cript_data[:51]
        iv = db_cript_data[51:67]
        footer = db_cript_data[-20:]

        with open(db_file, "rb") as fh:
            data = fh.read()

        aes = AES.new(key, mode=AES.MODE_GCM, nonce=iv)
        with open("msgstore.db.crypt12", "wb") as fh:
            fh.write(header + iv + aes.encrypt(zlib.compress(data)) + footer)

        print "Encrypted msgstore.db created."
    except Exception as e:
        print "An error has ocurred encrypting the Database:", e

**Comment by T-vK** [comment]
Awesome, thank you! So the header and footer actually stay the same even when the decrypted db was modified? That would be great. Maybe it would make sense to hardcode the whole header and footer into the script in that case? And maybe the iv as well?

**Comment by B16f00t** [comment]
really the function of WhatsApp encrypting I do not know where it gets the values ​​of the header, IV, footer.  when the database is decrypted do not use those header, IV, footer. I add from the other encrypted database .
I figure out the information in this article.
https://stackpointer.io/security/decrypt-whatsapp-crypt12-database-messages/559/
