### ISSUE TITLE
thank you, & 2 issues.

### ISSUE THREAD

**Issue by andwan0** [B16f00t/whapa#152]
BIG THANK YOU to original authors/collab/developers putting this toolkit together.

------

I have 2 versions of the same DB (old original... and a new version but with lots of chats deleted).

I notice we can use try/catch around each for loop BODY. This will just bypass duplicates if the id/row already exists. (kinda like an update in a file/folder diff/compare app).

I notice we are trying to insert into a database VIEW. This is readonly?

ISSUE 1: We can manually eyeball and sync the table col headers (some tables have new cols). Am I right we can include ALL the columns? ie new columns?

ISSUE 2: Currently we are merging 4 main tables (messages, thumbnails, chat, quotes). But there are other tables (calls, etc.). Can I copy the logic and merge these tables too?

**Comment by B16f00t** [comment]
You can merge all the tables you are interested in.
When I created the 'merge', I made it partial only with the tables of interest to get the chats, not to restore backups.
If someone wants to update the code, I'll do a PR without problem
