### ISSUE TITLE
 Error -3 while decompressing data: incorrect header check

### ISSUE THREAD

**Issue by Mrakobes666** [B16f00t/whapa#156]
Please make changes to the configuration file

**Comment by Thejas04** [comment]
hello did you get any solution I am also getting the same error if you anything please update me it will help a lot?

**Comment by Baneeishaque** [comment]
I think it is related to [Update the new crypt 14 offset! #147](https://github.com/B16f00t/whapa/issues/147).

**Comment by B16f00t** [comment]
#128
