### ISSUE TITLE
Error during decrypt ( expected str, bytes or os.PathLike object, not NoneType )

### ISSUE THREAD

**Issue by ShadabFaiz** [B16f00t/whapa#158]
Setup:
OS: Ubutun 18 LTS On WSL
Python version: 3.9.0
![Capture](https://user-images.githubusercontent.com/8160121/160288808-10ff8c8b-91ca-4c15-b3fa-9d176ee606ba.PNG)

**Comment by B16f00t** [comment]
Maybe your file size is zero
