### ISSUE TITLE
[e] Error 'backupFrequency'

### ISSUE THREAD

**Issue by gabrielbandeira80** [B16f00t/whapa#159]
[-] Whatsapp version: 2.22.6.72-play-release
[-] Backup upload   : 2022-03-28T13:43:19.226504Z
[-] Backup size     : 9585729222 Bytes (8 GB)
[+] Backup metadata
[e] Error 'backupFrequency'

**Comment by B16f00t** [comment]
If you are getting Error Backup Frequency, it is possible that you have the backup with password, so you have to change the permissions and try again.
