### ISSUE TITLE
Add Feature: Enable to download any appdata from drive

### ISSUE THREAD

**Issue by harsh1412** [B16f00t/whapa#16]
Hey there,
This work great.  Can you add a feature to download custom package files?
Like way back HIKE had some appdata backup on drive and i want to try fetching it.
I tried this[ scrip](https://github.com/nelenkov/gdrive-appdata)t but it seems to not working giving 403 forbidden error.
I don't think it is maintained anymore.

**Comment by B16f00t** [comment]
It's a good idea, but this project is related only with Whatsapp.
Maybe can code another project for this, Thanks,
