### ISSUE TITLE
MacOS - Alternative to reinstalling python for tk

### ISSUE THREAD

**Issue by XuluWarrior** [B16f00t/whapa#161]
As suggested in #92 the docs say to uninstall the homebrew python and install it from the official binaries.

An alternative to this is to install `python-tk`. i.e.
```
brew install python-tk
```

**Comment by XuluWarrior** [comment]
I'm not sure what you're asking.

Do you mean, does this command work on a Mac?
Yes, this is a Mac specific command assuming you've installed Homebrew (https://brew.sh)

Do you mean, does this project work on a Mac?
Yes, as long as you follow the instructions in the Readme.  The command above is an alternative to uninstalling python if you have previously installed it using Homebrew.

**Comment by gabrielbandeira80** [comment]
for windows and linux an error occurs.

[-] Whatsapp version: 2.22.6.72-play-release
[-] Backup upload : 2022-03-28T13:43:19.226504Z
[-] Backup size : 9585729222 Bytes (8 GB)
[+] Backup metadata
[e] Error 'backupFrequency'

**Comment by XuluWarrior** [comment]
If you have a problem running it on Windows and Linux then you should create a new issue.  See the `New Issue` button in the top right of the page.

**Comment by B16f00t** [comment]
I'll modify readme file, Thanks @XuluWarrior
