### ISSUE TITLE
Requesting Google access... Failed

### ISSUE THREAD

**Issue by joeleskratos** [B16f00t/whapa#165]
yeah this I don't have 2FA on my account and I have already done the most obvious step This https://accounts.google.com/b/0/DisplayUnlockCaptcha To my account but still, I have the same problem since yesterday never happen this before 😪

**Comment by r-cosiocastro** [comment]
I got this problem too, I guess it has to do something with Google and 3rd party apps...

**Comment by joeleskratos** [comment]
> I got this problem too, I guess it has to do something with Google and 3rd party apps...

Im really happy I'm not alone, then yeah I think the same thing google have done something so  we have to wait until they fix it I mean the creators of whapa :c

**Comment by rodrigopar99** [comment]
Yeah this is something that's happening to me since yesterday.

**Comment by joeleskratos** [comment]
> Yeah this is something that's happening to me since yesterday.

Yes we can only wait until they fix it cuz I have done everything I can but it doesn't work that's why I opened this issue but I see I'm not alone with the problem yeah since yesterday I had the problem :C

**Comment by ale499** [comment]
yeah me too

**Comment by joeleskratos** [comment]
> 

Good to hear this so  we are not the only ones having this problem :c

**Comment by gabrielbandeira80** [comment]
yeah me too 👍

**Comment by User1920ca** [comment]
same problem too

**Comment by FelipeCJSEP** [comment]
same problem here

**Comment by chukfart** [comment]
mismo problema

**Comment by joeleskratos** [comment]
> 

Que raro no amigo ? Yo creo que algo ha hecho google para que el sistema este no entre seguro han mejorado la seguridad :c

**Comment by gabrielbandeira80** [comment]
si Yo creo tambien

**Comment by joeleskratos** [comment]
> si Yo creo tambien

hay q esperar no mas

**Comment by B16f00t** [comment]
It seems that something has changed on the part of Google authentication.
There is a problem with the Gpsoauth library that Whapa uses to authenticate itself. 
If the library is not updated soon, an alternative method will have to be found.

**Comment by pabisky** [comment]
Pense que era el único con el problema del error de autorización de google, a veces lo solucionaba actualizando pero ahora no me funciona nada.  A esperar que reparen el problema.

**Comment by joeleskratos** [comment]
> It seems that something has changed on the part of Google authentication. There is a problem with the Gpsoauth library that Whapa uses to authenticate itself. If the library is not updated soon, an alternative method will have to be found.
i rally hope u find an alternative method 


> It seems that something has changed on the part of Google authentication. There is a problem with the Gpsoauth library that Whapa uses to authenticate itself. If the library is not updated soon, an alternative method will have to be found.

i really hope the u find an alternative method but take  ur time

**Comment by joeleskratos** [comment]
> Pense que era el único con el problema del error de autorización de google, a veces lo solucionaba actualizando pero ahora no me funciona nada. A esperar que reparen el problema.

Si amigo el creador de whapa ya sabe del problema seguro en unos dias lo arregla dice el

**Comment by User1920ca** [comment]
no solution yet?

**Comment by Maro8311** [comment]
Exwa from Elcomsoft does the authentication correctly, but I do not know how to perform a MITM-Attack (i.e. with Frida server) on this program. Seems to use certificate pinning. If anyone has an idea/a hint how to do this? 

Did not try MITM-Attack on WhatsApp itself yet!

**Comment by TonyStage** [comment]
Tengo el mismo problema,  cuando se solucione  lo dirán por aquí?

**Comment by TonyStage** [comment]
¿Alguien sabe de otra alternativa? O le ha funcionado algo más? Does anyone know of another alternative? Or has something else worked?

**Comment by joeleskratos** [comment]
> Tengo el mismo problema, cuando se solucione lo dirán por aquí?

Ya van varios dias y aun no lo arreglan :c

**Comment by joeleskratos** [comment]
> 

no conosco otro metodo pero se que por aca van a decir si lo han arreglado luego a descargar la nueva version

**Comment by gabrielbandeira80** [comment]
estamos esperando una nueva actualizacion

**Comment by gabrielbandeira80** [comment]
estamos esperando una nueva actualizacion

**Comment by rodrigopar99** [comment]
> Exwa from Elcomsoft does the authentication correctly, but I do not know how to perform a MITM-Attack (i.e. with Frida server) on this program. Seems to use certificate pinning. If anyone has an idea/a hint how to do this?
> 
> Did not try MITM-Attack on WhatsApp itself yet!

True, Exwa from Elcomsoft still works as usual, I'm not sure if they developed their own way in order to log-in (which can handle the new auth process) or they have a special certificate.

**Comment by Kakaroto43** [comment]
ahora si ya nos dejaron varios días sin el método... alguien sabe algo, si ya pronto lo solucionaran??

saludos.

**Comment by r-cosiocastro** [comment]
> ahora si ya nos dejaron varios días sin el método... alguien sabe algo, si ya pronto lo solucionaran??
> 
> saludos.

Ya dijeron más arriba que es un asunto de la librería Gpsoauth, ten paciencia y espera a que la actualicen.

**Comment by joeleskratos** [comment]
> > ahora si ya nos dejaron varios días sin el método... alguien sabe algo, si ya pronto lo solucionaran??
> > saludos.
> 
> Ya dijeron más arriba que es un asunto de la librería Gpsoauth, ten paciencia y espera a que la actualicen.

ok esta bien a solo esperar  :v

**Comment by Maro8311** [comment]
> > Exwa from Elcomsoft does the authentication correctly, but I do not know how to perform a MITM-Attack (i.e. with Frida server) on this program. Seems to use certificate pinning. If anyone has an idea/a hint how to do this?
> > Did not try MITM-Attack on WhatsApp itself yet!
> 
> True, Exwa from Elcomsoft still works as usual, I'm not sure if they developed their own way in order to log-in (which can handle the new auth process) or they have a special certificate.

Update. Exwa is not working in the moment, error message: 'Connection to server lost.' Even with valid binary authentication token. I guess the gpsoauth update wil take quite some time.

**Comment by joeleskratos** [comment]
> > > Exwa from Elcomsoft does the authentication correctly, but I do not know how to perform a MITM-Attack (i.e. with Frida server) on this program. Seems to use certificate pinning. If anyone has an idea/a hint how to do this?
> > > Did not try MITM-Attack on WhatsApp itself yet!
> > 
> > 
> > True, Exwa from Elcomsoft still works as usual, I'm not sure if they developed their own way in order to log-in (which can handle the new auth process) or they have a special certificate.
> 
> Update. Exwa is not working in the moment, error message: 'Connection to server lost.' Even with valid binary authentication token. I guess the gpsoauth update wil take quite some time.

OMg that is sooo sad :c

**Comment by TonyStage** [comment]
@joeleskratos si encuentras alguna otra manera de descargar la copia de seguridad,  me la podrías comentar por favor?

**Comment by joeleskratos** [comment]
> @joeleskratos si encuentras alguna otra manera de descargar la copia de seguridad, me la podrías comentar por favor?

Yo estoy tan perdido como tu no se ni como funciona la aplicacion whapa internamente :c solo vi un tuto y lo usaba

**Comment by Kakaroto43** [comment]
> > @joeleskratos si encuentras alguna otra manera de descargar la copia de seguridad, me la podrías comentar por favor?
> 
> Yo estoy tan perdido como tu no se ni como funciona la aplicacion whapa internamente :c solo vi un tuto y lo usaba

todos estamos en la misma, no hay otra forma a menos que tengas el cel. físicamente

**Comment by allamch** [comment]
ANY SOLUTION YET ??

**Comment by gabrielbandeira80** [comment]
no sirve de nada quedarse aquí preguntando todo el tiempo, cuando tenga una solución el desarrollador le informará.

**Comment by Maro8311** [comment]
> > > > Exwa from Elcomsoft does the authentication correctly, but I do not know how to perform a MITM-Attack (i.e. with Frida server) on this program. Seems to use certificate pinning. If anyone has an idea/a hint how to do this?
> > > > Did not try MITM-Attack on WhatsApp itself yet!
> > > 
> > > 
> > > True, Exwa from Elcomsoft still works as usual, I'm not sure if they developed their own way in order to log-in (which can handle the new auth process) or they have a special certificate.
> > 
> > 
> > Update. Exwa is not working in the moment, error message: 'Connection to server lost.' Even with valid binary authentication token. I guess the gpsoauth update wil take quite some time.
> 
> OMg that is sooo sad :c

Update #2 Exwa works again

**Comment by TonyStage** [comment]
New notices?   Alguien sabe algo?

**Comment by joeleskratos** [comment]
> New notices? Alguien sabe algo?

nada hermano :c estamos esperando

**Comment by Kakaroto43** [comment]
> New notices? Alguien sabe algo?

nada, seguimos en espera, por el momento solo el Exwa está funcionando.

**Comment by joeleskratos** [comment]
> > New notices? Alguien sabe algo?
> 
> nada, seguimos en espera, por el momento solo el Exwa está funcionando.

Que es el EXwa ?

**Comment by Kakaroto43** [comment]
> Exwa from Elcomsoft

Exwa from Elcomsoft .. es lo mismo nada más q es un programita de paga..

**Comment by User1920ca** [comment]
no solution yet?

**Comment by Maro8311** [comment]
> > Exwa from Elcomsoft
> 
> Exwa from Elcomsoft .. es lo mismo nada más q es un programita de paga..

not open source, but works without paying

**Comment by B16f00t** [comment]
New version working v1.58

**Comment by B16f00t** [comment]
I close the issue, if you continue with problems, join to the channel https://t.me/+R3cjyu5EPN3lSA3k

**Comment by User1920ca** [comment]
i downloaded the new version and i have this problem
Traceback (most recent call last):
  File "D:\whapa-master\libs\whagodri.py", line 12, in <module>
    from configobj import ConfigObj
ModuleNotFoundError: No module named 'configobj'

**Comment by B16f00t** [comment]
Please read the readme. You must install requirements

**Comment by joeleskratos** [comment]
gg

**Comment by Maro8311** [comment]
> i don't know if it should be closed cuz now people cant use it without a phone verification its not like the older one :c Google sucks

Yes, but Exwa from Elcomsoft (no advertising) does it without phone verification, but I cannot perform a MITM-Attack with Frida Server on this application due to certificate pinning. If anyone knows how to use Frida server on Windows applications held is appreciated! But little caveat of Exwa: it cannot download the PTT*.opus recordings, these files are 0 Bytes in size, dont know why, but the rest works. Try the trial version and test yourself, you can use Everything from Voidtools to see in what directory the files are downloaded. Because the viewing capability in the program is limited,, cause its a trial. But you can view everything directly in the filesystem.

**Comment by B16f00t** [comment]
For now this is the only method I have been able to get it to work, if a new method is obtained, like the previous one it will be improved.

**Comment by Maro8311** [comment]
> For now this is the only method I have been able to get it to work, if a new method is obtained, like the previous one it will be improved. I don't make money with this, whoever doesn't like it should use Exwa from Elcomsoft,

I think we all appreciate your work here. Thanks a a lot of for your update and sharing. I think no one can and will DEMAND a solution from you. I would like to collaborate on a solution without phone verification, thats why I brought Exwa into play (not to critize your solution), to show it must be possible. But exwa is not open source and not scriptable and as such at least not my desired solution. I was stuck on listening to Exwa. I will try if listening to the native WhatsApp on Android is easier (and break the certificate pinning). But I do not think it is easier! If someone has information in these issues, plz share!

**Comment by joeleskratos** [comment]
> For now this is the only method I have been able to get it to work, if a new method is obtained, like the previous one it will be improved. I don't make money with this, whoever doesn't like it should use Exwa from Elcomsoft,
yeah I really appreciate ur work all of us do and I'm no one tell you if it's wrong or not but yeah time will tell if u can see how  Exwa is making it to work without phone verification 😥

**Comment by B16f00t** [comment]
It is not that difficult, for example, for WhatsApp on Android I use a virtual machine with android 6 and I use the canary application which install a certificate to listen to the traffic.  Yesterday I was testing exwa and  it didn't work for me, it displayed me a connection failure to the server.  If I know you can find another method, it is welcome, but for now it is what it is

**Comment by B16f00t** [comment]
A new version is available where no browser is needed.

**Comment by joeleskratos** [comment]
> A new version is available where no browser is needed.

and the phone verification?

**Comment by Maro8311** [comment]
> > A new version is available where no browser is needed.
> 
> and the phone verification?

At least on my first try, phone veri was gone!

**Comment by Maro8311** [comment]
> A new version is available where no browser is needed.

Thx a lot @B16f00t

The guys from gspsoauth did some contributions too. What the the trick? The new user-agent?
