### ISSUE TITLE
"Error: no such table: messages"

### ISSUE THREAD

**Issue by skajabel** [B16f00t/whapa#166]
I've been getting the message since this week: "Error: no such table: messages"
Has anything changed?

**Comment by B16f00t** [comment]
Can you specify a bit more, what utility were you using from the suite?

**Comment by skajabel** [comment]
version 1.57
I can decrypt the file with WhaCipher to msgstore.db.
When I want to parse the db-file with WhaPa, the error message: "Error: no such table: messages"
If I use older files, then it works.

**Comment by B16f00t** [comment]
Ok I'll chek the new tables

**Comment by B16f00t** [comment]
#164
