### ISSUE TITLE
whagodri.py - --s_databases Not Working Correctly

### ISSUE THREAD

**Issue by dbmaxpayne** [B16f00t/whapa#169]
Hi,

just found out that apparently media files are now named .mcrypt1 (with E2E enabled) which make --s_databases sync everything, not just the databases.
I suggest changing the following line

`if "crypt" in i:`
to
`if "crypt" in i and "mcrypt" not in i:`

Surely there is a better solution, but that has worked for me for now.

Cheers,
Mark

**Comment by B16f00t** [comment]
Thanks, do you want to do a PR? It's welcome

**Comment by B16f00t** [comment]
Fixed. Thanks
