### ISSUE TITLE
Error=NeedsBrowser

### ISSUE THREAD

**Issue by chhanganivarun** [B16f00t/whapa#17]
The following message (with different plt) keeps coming even after google says:
```
Account access enabled

Please try signing in to your Google account again from your new device or application.
```

The message:
```
     __      __.__             ________      ________        .__ 
    /  \    /  \  |__ _____   /  _____/  ____\______ \_______|__|
    \   \/\/   /  |  \\__  \ /   \  ___ /  _ \|    |  \_  __ \  |
     \        /|   Y  \/ __ \\    \_\  (  <_> )    `   \  | \/  |
      \__/\  / |___|  (____  /\______  /\____/_______  /__|  |__|
           \/       \/     \/        \/              \/          

    ------------ Whatsapp Google Drive Extractor v0.1 ------------
    
[i] Searching...

Error=NeedsBrowser
Url=https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/auth?hl%3Den%26xoauth_display_name%3DAndroid%2BLogin%2BService%26source%3DAndroid%2BLogin&plt=A******************************************************************************************************************************************v
ErrorDetail=To access your account, you must sign in on the web. Touch Next to start browser sign-in.
```

**Comment by B16f00t** [comment]
Follow this:

1.    Disable 2FA in your Google Account
2.  Download the latest version of whagdext.py
3.   Install the requirements
4.    Configure:
    Edit only the values of the./cfg/settings.cfg file
    [auth]
    gmail = alias@gmail.com
    passw = yourpassword
    devid = Device ID (optional, if specified get more information)
    celnumbr = BackupPhoneNumber (ex. 3466666666666, no +, nor 00)
5.   Use on a terminal: python3 whagdext.py -list.
6.    If you request it, log in to your browser and then click here, https://accounts.google.com/DisplayUnlockCaptcha.
7.    If it lists all the files in the account then try the '-sync' flag.
8.    Try another account if it's possible to see if the error continues.
