### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by TehBotolSosro** [B16f00t/whapa#2]
whademe.py
  File "D:\whapa-master\whademe.py", line 53
    ------------ Whatsapp Decrypter and Merger v""" + version + """ ------------
                                                  ^
SyntaxError: invalid syntax

Windows 10 x64 + Python 3.6

**Comment by randmxguy** [comment]
File "whagodri.py", line 36
    ------------ Whatsapp Google Drive Extractor v""" + version + """ ------------
                                                    ^
SyntaxError: invalid syntax
How about whagodri.py?
Also Windows 10 x64 + Python 3.6

**Comment by B16f00t** [comment]
You must use python2
