### ISSUE TITLE
does the script still working?

### ISSUE THREAD

**Issue by trisnaw** [B16f00t/whapa#21]
I've used whatsappgdextract for some time ago (last time I used it, it worked) and suddenly it doesn't work anymore so I try this script and the result is still the same, " Unable to locate google drive file map for: com.whatsapp "

**Comment by B16f00t** [comment]
The script works perfectly.
Use the last version of whagodri.py
1. Disable 2FA in your Google Account.
2. Install the requirements.
 Edit the values of the./cfg/settings.cfg file.
   gmail = alias@gmail.com
   passw = yourpassword
   devid = Device ID (optional, if specified get more information)
   celnumbr = BackupPhoneNumber  (ex. 3466666666666, [Country Code] + Phone Number 'not +, nor 00
Log into your browser and then allow access to your Google account.
 https://accounts.google.com/DisplayUnlockCaptcha
