### ISSUE TITLE
Ssl certificate error

### ISSUE THREAD

**Issue by DMartinezSilva** [B16f00t/whapa#217]
Requests can't Locate ssl certificate issuer

**Comment by DMartinezSilva** [comment]
![1717749207326465511107823842175](https://github.com/B16f00t/whapa/assets/82400489/018503db-42bb-4d90-8afb-55ccf137c246)

**Comment by guilhergomes** [comment]
same problem

**Comment by DMartinezSilva** [comment]
https://medium.com/@vkmauryavk/resolving-sslcertverificationerror-certificate-verify-failed-unable-to-get-local-issuer-515d7317454f

**Comment by rschu68** [comment]
https://medium.com/@vkmauryavk/resolving-sslcertverificationerror-certificate-verify-failed-unable-to-get-local-issuer-515d7317454f
