### ISSUE TITLE
[e] Unable to locate google drive file map for: com.whatsapp

### ISSUE THREAD

**Issue by teasider** [B16f00t/whapa#23]
This only appeared lately, is this a change on google's side?

**Comment by TehBotolSosro** [comment]
same here, it worked on my old account. but in my other two new account it get that error,
seem something new is changed as it worked fine a month ago

**Comment by B16f00t** [comment]
I'm going to update a new version, check it and feedback. pls

**Comment by TehBotolSosro** [comment]
still the same error

`     __      __.__             ________      ________        .__
    /  \    /  \  |__ _____   /  _____/  ____\______ \_______|__|
    \   \/\/   /  |  \\__  \ /   \  ___ /  _ \|    |  \_  __ \  |
     \        /|   Y  \/ __ \\    \_\  (  <_> )    `   \  | \/  |
      \__/\  / |___|  (____  /\______  /\____/_______  /__|  |__|
           \/       \/     \/        \/              \/

    ------------ Whatsapp Google Drive Extractor v1.1 ------------

[i] Searching...

[e] Unable to locate google drive file map for: com.whatsapp`

i also tried to rebackup in case the backup are corrupted and still the same error

**Comment by B16f00t** [comment]
Ok Talk to me by telegram, I'll modified the script again and when it
works, I'll upload the new version

**Comment by TehBotolSosro** [comment]
@B16f00t ok sent you a message on telegram, thanks

**Comment by B16f00t** [comment]
Fixed in new version 1.1
