### ISSUE TITLE
Cant find download file

### ISSUE THREAD

**Issue by mfali728** [B16f00t/whapa#27]
it's saying 

[i] Searching...

[e] Error:  Requested entity was not found.
[e] Unable to locate google drive file map for: com.whatsapp <Response [404]>
[i] Generating threads...
[+] Backup name : clients/wa/backups/92**********
[i] Downloads finished

but i am unable to find the downloaded file, there is no downloaded file in main folder

**Comment by TehBotolSosro** [comment]
have you try the alternative method?.

**Comment by B16f00t** [comment]
Alternative must works

**Comment by CUBOFIG** [comment]
I use the "WhatsApp-GD-Extractor-Multithread" and it also has the same error, will it be a unit modification or whatsapp?

**Comment by B16f00t** [comment]
WhatsApp-GD-Extractor-Multithread doesn't work.
Whagodri at alternative mode works perfectly
