### ISSUE TITLE
Download only Images folder

### ISSUE THREAD

**Issue by altgiu** [B16f00t/whapa#28]
How i can download only images folder or only images sent?

**Comment by B16f00t** [comment]
I'll add it to the script

**Comment by B16f00t** [comment]
New update incorporates the improvement

**Comment by altgiu** [comment]
When i tray to download only images return this error

Traceback (most recent call last):
  File ".\libs\whagodri.py", line 309, in <module>
    if i.split("/")[6] == ".Statuses" or i.split("/")[6] == "WhatsApp Images" or
 i.split("/")[6] == "WhatsApp Stickers" or i.split("/")[6] == "WhatsApp Profile
Photos" or i.split("/")[6] == "WallPaper":
IndexError: list index out of range"

**Comment by B16f00t** [comment]
Get in touch by telegram

**Comment by B16f00t** [comment]
Fixed in v1.14
