### ISSUE TITLE
wagodri - can't recover a probably incomplete backup

### ISSUE THREAD

**Issue by ghost** [B16f00t/whapa#30]
I'm trying to recover a backup from an old device that was probably interrupted before it finished. I can see the backup on the google drive webpage, but the app gives me those errors:
```
[e] No Google Drive backup: 'files'                                                                                    
[e] Unable to locate google drive file map for: com.whatsapp <Response [200]>  
[-] Backup name   : clients/wa/backups/*number*
[-] Backup upload : *date*
[i] Error 'sizeBytes'
```
As you can see, even the app confirms the existence of the backup but cannot find the files. Those files must be somewhere in gdrive because the backup was almost complete when I turned off and then resetted the device (in fact, I even thought it was finished).
I think the app should be able to handle these situations.

Thank you in advance

**Comment by B16f00t** [comment]
Get in touch me by telegram

**Comment by B16f00t** [comment]
It seems that incomplete backup cannot be recovered.
