### ISSUE TITLE
problem installing requirements

### ISSUE THREAD

**Issue by pulp2010** [B16f00t/whapa#32]
Hi, I'm using Python38-32 with PIP 19.2.3 and I'm getting error:

![image](https://user-images.githubusercontent.com/57273686/68059330-694b2000-fcfc-11e9-85c1-2349e0b9a87a.png)

Any ideas what's wrong? I'm using windows 7 pro but *uck it :)

**Comment by B16f00t** [comment]
I think you have a bad python installation. Try another version

**Comment by ParikhKadam** [comment]
@pulp2010 Download and install visual c++ 14.0 on your PC in order to build this particular requirement.

**Comment by dilinjabass** [comment]
pycryptodome just released a version compatible for python3.8 - it should be working now.
If not, install pycryptodome from the wheel file
[https://pypi.org/project/pycryptodome/3.9.1/#files](https://pypi.org/project/pycryptodome/3.9.1/#files)
Find the compatible file for your version of python, win, linux etc. cp38 is for python3.8, cp37 is for python3.7 etc

If you still cant get it to work for python3.8, then fall back to 3.7 as there should be no bugs

**Comment by dilinjabass** [comment]
And to install the wheel file, download it. Open terminal where the file is and use
**pip3 install some-package.whl** (copy paste the full wheel file name in place of 'some-package')
