### ISSUE TITLE
Unable to locate google drive file map for: com.whatsapp <Response [200]>

### ISSUE THREAD

**Issue by dilinjabass** [B16f00t/whapa#35]
I've tested this on multiple backups and accounts. A few work, but the majority bring up this error
**Unable to locate google drive file map for: com.whatsapp <Response [200]>**

I'm not certain about this but I think older backups (I tested one from february 2019) work. But the newer ones are not finding the backup. Must be a google update?

**Comment by B16f00t** [comment]
Yeah, maybe I'll try to figure it out.

**Comment by dilinjabass** [comment]
So I just checked my account that was backed up yesterday and it worked fine. So my theory that maybe it was just newer backups doesn't hold up.

I do not understand why some work and most don't.

**Comment by dilinjabass** [comment]
Unable to locate google drive file map for: com.whatsapp <Response [200]>
[-] Backup upload : 2019-10-30T11:43:54.544Z
[i] Error 'sizeBytes'

[-] Backup upload : 2019-01-02T15:38:14.119350Z
[i] Error 'sizeBytes'

Two different backups, different time periods. the Error 'sizeBytes' mean anything at all?

**Comment by B16f00t** [comment]
It seems that the backup is corrupt.
