### ISSUE TITLE
Unable to locate google drive file map for : Com.Whatsapp

### ISSUE THREAD

**Issue by krish74** [B16f00t/whapa#39]
Hello Team,

I'm new to this site and I have searched for few options where I could download the backup whatsapp data from the google drive and that's how I came to know from one of the youtuber about the WhatsappGDExtract. I did everything installed up to date and tried it with one of my account which did not work and came out with this message as " Unable to locate google drive file map for : Com.Whatsapp. But the same I tried with my different account which worked. Please help me out in recovering the data. Where could the problem be ..?

**Comment by B16f00t** [comment]
#34
