### ISSUE TITLE
KeyError item

### ISSUE THREAD

**Issue by jahmartin** [B16f00t/whapa#4]
Hi, I have the following error {u'error ': {u'code': 400, u'message ': u'Invalid query', u'errors': [{u'locationType ': u'parameter', u'domain ': u'global', u'message ': u'Invalid query', u'reason ': u'invalid', u'location ': u'q'}]}}
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid query",
    "locationType": "parameter",
    "location": "q"
   }
  ],
  "code": 400,
  "message": "Invalid query"
 }
}

Traceback (most recent call last):
  File "whagodri.py", line 287, in <module>
    drives = gDriveFileMap ()
  File "whagodri.py", line 150, in gDriveFileMap
    for result in jres ['items']:
KeyError: 'items'

Could you help me solve it? Thanks

**Comment by B16f00t** [comment]
You must use python2, and set 'settings.cfg' file.  Phone = country code + phone number

**Comment by jahmartin** [comment]
I have already entered that values ​​in the settings file and I am using the version of python that you occupy but still the error continues

**Comment by jahmartin** [comment]
I get the following error Error=NeedsBrowser

**Comment by B16f00t** [comment]
You must press the link that shows to login and re-run the program
