### ISSUE TITLE
Windows could not connect to the group policy client service

### ISSUE THREAD

**Issue by demoo1403** [B16f00t/whapa#40]
When i logon to my computer this message appears to me in the toolbar "Windows could not connect to the group policy client service"
And when i try to open my computer folder or any thing this message appears to me "The device is not ready" 
Please help me guys
![IMG_20191204_144641](https://user-images.githubusercontent.com/57749760/70372548-1f4fee00-18e9-11ea-9b93-ef38b99eba24.jpg)
![Uploading IMG_20191204_144656.jpg…]()
![Uploading IMG_20191204_144627.jpg…]()

**Comment by B16f00t** [comment]
Does this mistake have anything to do with Whapa?

**Comment by aamhm** [comment]
u have a another problem not related to the program
