### ISSUE TITLE
another Google Backup

### ISSUE THREAD

**Issue by aamhm** [B16f00t/whapa#41]
i like the application that can download and read whatsapp Backup
but i'm asking you ,is there a way to download the Android Phone Backup that beside the whatsapp Backup ,do u have a solution for it?
![Phone Backup2](https://user-images.githubusercontent.com/39556627/71203094-0b6f9900-22a6-11ea-94ef-105cff2a8b9a.jpg)

**Comment by unixsaurav** [comment]
Did you get any solution? i really need it.

**Comment by B16f00t** [comment]
There is a solution but whapa is only designed to download the whatsapp account in google.
