### ISSUE TITLE
com.whatsapp <Response [200]>

### ISSUE THREAD

**Issue by viruzx01** [B16f00t/whapa#43]
No Google Drive backup: 'files'
[e] Unable to locate google drive file map for: com.whatsapp <Response [200]>
[-] Backup name   : clients/wa/backups/5216441720530
[-] Backup upload : 2020-01-12T20:42:18.998Z
[i] Error 'sizeBytes'

Where is the problem? :)

**Comment by TehBotolSosro** [comment]
did you try the alternate download method
