### ISSUE TITLE
Unable to locate google drive file map for: com.whatsapp urgent help!!

### ISSUE THREAD

**Issue by marshcu** [B16f00t/whapa#44]
I do not longer have the same phone number I used on my WhatsApp account, I had to beg an stranger to give me the verification code in order to get my account back. For some reason I wasn't able to restore my messages nor from my phone database nor from google drive database. Since someone else already had my number I didn't want to try again by uninstalling and restalling so I changed the number on the account right away. When I did it, again non of my messages nor my contacts restored. Now the database on my phone is gone but I still have the one on drive with my previous number. I have been trying this method to at least have access to my old messages but im getting the "Unable to locate google drive file map for: com.whatsapp" error. I dont know if I should write in the settings.cfg my actual or previous phone number (the one in the drive database), either way none of them seem to be working as I get the same error. I still have the same phone so I guess the devid is the same as it was before. English is not my first language and I know nothing about programming but getting my messages back is really important to me, any help you can give will be greatly appreciated!

**Comment by aamhm** [comment]
> I do not longer have the same phone number I used on my WhatsApp account, I had to beg an stranger to give me the verification code in order to get my account back. For some reason I wasn't able to restore my messages nor from my phone database nor from google drive database. Since someone else already had my number I didn't want to try again by uninstalling and restalling so I changed the number on the account right away. When I did it, again non of my messages nor my contacts restored. Now the database on my phone is gone but I still have the one on drive with my previous number. I have been trying this method to at least have access to my old messages but im getting the "Unable to locate google drive file map for: com.whatsapp" error. I dont know if I should write in the settings.cfg my actual or previous phone number (the one in the drive database), either way none of them seem to be working as I get the same error. I still have the same phone so I guess the devid is the same as it was before. English is not my first language and I know nothing about programming but getting my messages back is really important to me, any help you can give will be greatly appreciated!

i use it with no problem as long as you have your username and password on google drive
i can help you throught Discord chat if u want or facebook messenger aamhm@yahoo.com
