### ISSUE TITLE
Chat DB Size 0

### ISSUE THREAD

**Issue by DarioCvarku** [B16f00t/whapa#48]
Hello,
When I run "python whagodri.py -i" this shows up:

>      __      __.__             ________      ________        .__ 
>     /  \    /  \  |__ _____   /  _____/  ____\______ \_______|__|
>     \   \/\/   /  |  \\__  \ /   \  ___ /  _ \|    |  \_  __ \  |
>      \        /|   Y  \/ __ \\    \_\  (  <_> )    `   \  | \/  |
>       \__/\  / |___|  (____  /\______  /\____/_______  /__|  |__|
>            \/       \/     \/        \/              \/          
> 
>     -------------- Whatsapp Google Drive Extractor --------------
> [i] Searching...
> 
> [-] Backup name   : clients/wa/backups/{myPhoneNumber}
> [-] Backup upload : 2020-01-14T10:06:21.207304Z
> [-] Backup size   : 7975615269 Bytes (7606.14 MB)
> [+] Backup metadata
>     [-] Backup Frequency         : 1 
>     [-] Backup Network Settings  : 0 
>     [-] Backup Version           : 1 
>     [-] Include Videos In Backup : True 
>     [-] Num Of Photos            : 24169
>     [-] Num Of Media Files       : 30555
>     [-] Num Of Messages          : 953684
>     [-] Video Size               : 3182997101 Bytes (3035.54 MB)
>     [-] Backup Size              : 7975615269 Bytes (7606.14 MB)
>     [-] Media Size               : 7974765941 Bytes (7605.33 MB)
>     [-] Chat DB Size             : 0 Bytes (0.00 KB)

"Chat DB Size" is 0 Bytes, but Num Of Messages is 953684.
How can I restore my chat? 
When pulling everything, the only things I get are:

>      __      __.__             ________      ________        .__ 
>     /  \    /  \  |__ _____   /  _____/  ____\______ \_______|__|
>     \   \/\/   /  |  \\__  \ /   \  ___ /  _ \|    |  \_  __ \  |
>      \        /|   Y  \/ __ \\    \_\  (  <_> )    `   \  | \/  |
>       \__/\  / |___|  (____  /\______  /\____/_______  /__|  |__|
>            \/       \/     \/        \/              \/          
> 
>     -------------- Whatsapp Google Drive Extractor --------------
> [i] Searching...
> 
> [+] Backup name : clients/wa/backups/{myPhoneNumber}
>     [-] File 1/30559  : Backups/chatsettingsbackup.db.crypt1
>     [-] File 2/30559  : Backups/statusranking.db.crypt1
>     [-] File 3/30559  : Backups/stickers.db.crypt1

All the other stuff is Media.

Any solution?
Thanks

**Comment by B16f00t** [comment]
The information shown is obtained from the request made to this url clients/wa/backups/34678410775, which is a file that keeps all the information of the backup.
 
In the whagodri tab you have two options to view your backup if it is not corrupt.
* click on list whatsapp database file
and you'll see the actual size of the backup chat.
* Download -> File: Databases/msgstore.db.crypt12
to download the backup.
If the size is 0, the file is corrupt, because of an incomplete backup.
