### ISSUE TITLE
Missing column

### ISSUE THREAD

**Issue by Eerosal** [B16f00t/whapa#5]
Hi.

I tried merging 2 backups with Whademe and the script threw error about missing columns. The columns were located in chatlist and started with "deleted_". However the older backup had them. I added the colums manually to new backup and the error didn't appear anymore. I tried restoring the database but it was corrupted.

'deleted_message_id','deleted_starred_message_id', 'deleted_message_categories'

**Comment by B16f00t** [comment]
ok I guess the msgstore.db will have been updated with more columns, anyway, the program just joins the most interesting to be able to analyze with whapa, it was never tested to restore a backup, I will review everything, and will enter a full merge, although this option could fail wheter enter new columns are inserted

**Comment by B16f00t** [comment]
Wamerge updated. It isn't valid with old copies.
