### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kkik2** [B16f00t/whapa#51]
Hi, I ran into this error. How do I fix it?

[e] Error:  Requested entity was not found.
[e] Unable to locate google drive file map for: com.whatsapp <Response [404]>
[i] Generating threads...
Traceback (most recent call last):
  File ".\libs\whagodri.py", line 313, in <module>
    getMultipleFiles(drives, bearer, files)
  File ".\libs\whagodri.py", line 166, in getMultipleFiles
    print("[+] Backup name : {}".format(drives["name"]))
KeyError: 'name'

**Comment by zaverichintan** [comment]
Enter country code in the of the number.
