### ISSUE TITLE
seems to work but this happens:

### ISSUE THREAD

**Issue by teasider** [B16f00t/whapa#52]
everything seems to work fine, but nothing is really happening. this is what the program replies:

issueAdvice=auto
Expiry=1588959205
ExpiresInDurationSec=3272
storeConsentRemotely=1
isTokenSnowballed=1
grantedScopes=https://www.googleapis.com/auth/drive.appdata [url]https://www.googleapis.com/auth/drive.file[/url]...... and a long key here.

anyone have any idea how to solve this?

**Comment by kinosheanic** [comment]
have you managed to figure it out?

**Comment by teasider** [comment]
> have you managed to figure it out?

Nope, still waiting for a reply.

**Comment by B16f00t** [comment]
Could you send me the full error, y modify that long key?

**Comment by teasider** [comment]
> Could you send me the full error, and modify that long key?
> Make sure to use the latest version of whapa v1.15 that fixed this problem

Updated to 1.15 and it now works, thank you.
