### ISSUE TITLE
Error=BadAuthentication

### ISSUE THREAD

**Issue by Gatsu84** [B16f00t/whapa#54]
It worked fine two days ago. Now I have this same error in any account. Did that happen to someone else?

**Comment by samson69** [comment]
same here

**Comment by FelipeCJSEP** [comment]
same here

**Comment by B16f00t** [comment]
Could you make a test?
Overwriting it will not work go to Google drive, delete manually backup and do it again via WhatsApp, And let me know

**Comment by samson69** [comment]
> Could you make a test?
> Overwriting it will not work go to Google drive, delete manually backup and do it again via WhatsApp, And let me know


    -------------- Whatsapp Google Drive Extractor --------------
[i] Searching...

Error=BadAuthentication


still same error

**Comment by samson69** [comment]
COMMON ISSUES
- Wrong email or password-> Error=BadAuthentication -> Check that your email and password are correct, if so change your google password and try again.

I am pretty sure, email and pass are correct. I've tried 3 other accounts, and the results are the same

**Comment by faouez15** [comment]
same problem

**Comment by vecchiobajker** [comment]
I have same issue Error=BadAuthentication

**Comment by aamhm** [comment]
i have the same issue  Error=BadAuthentication

**Comment by Kratos1098** [comment]
Heyyyy Hi B16f00t I'm actually having the same issue from like 3 days ago ''Error=BadAuthentication'' and I know its not a bad password or Gmail i try many sooooooo something else is going on here U.u we Need ur help I was searching in youtube a other guy has the same problem... U.u

**Comment by carlospakito05** [comment]
Yes,  i have the same problem. The password and numder its correct but appears the message ''Error=BadAuthentication'' with any account (incluiding my personal account). So please fix the tool.

**Comment by Kratos1098** [comment]
> Yes, i have the same problem. The password and numder its correct but appears the message ''Error=BadAuthentication'' with any account (incluiding my personal account). So please fix the tool.

Yeah aswell with my own account too GG we need help please u.u

**Comment by Kratos1098** [comment]
Nothing new still the same problem u.u

**Comment by bobfromghana** [comment]
same problem here

**Comment by Kratos1098** [comment]
U.u Omg still nothing

**Comment by faouez15** [comment]
Nothing new still the same problem

**Comment by Kratos1098** [comment]
Helpppppppppppp u.u

**Comment by galleryjathil** [comment]
still same problem, bad authen

**Comment by B16f00t** [comment]
Hey Guys, make a fresh install with python 3.7.7 to solve provisionally the issue

**Comment by bobfromghana** [comment]
> Hey Guys, make a fresh install with python 3.7.7 to solve provisionally the issue

confirmed working with python 3.77, thanks!

**Comment by Kratos1098** [comment]
B16f00t I love you okno Heheheh  B16f00t but tell me how do I install the new version of python I have to make a new installation of all i mean the python program and the whapa program  ? or I just install the new version of python overwriting like if it were an update?  Please tell me

**Comment by fresh2de** [comment]
@bobfromghana @B16f00t  can you please confirm the steps you took to solve the issue.. I tried installing 3.7.7 and still having the same issue

**Comment by carlospakito05** [comment]
Thank you, i updated phyton to 3.7.7 and the problem fix it. 
first go to (erase the spaces) https:// www. python. org/downloads/release/python-377/
and download "Windows x86-64 executable installer", install and keep your settings if the installer ask it. This solve the problem

**Comment by fresh2de** [comment]
@carlospakito05  Thank you!!

**Comment by michaelsibarani** [comment]
in my pc always show like this:
[e] Error:  Requested entity was not found.
[e] Unable to locate google drive file map for: com.whatsapp <Response [404]>
[i] Error 'name'

How fix this?

**Comment by B16f00t** [comment]
You have a wrong phonenumber, check the phone or your country code.

**Comment by carlospakito05** [comment]
If says: Unable to locate google drive file map for: com.whatsapp means that the google account dont have a whatsapp backup for decript.

**Comment by faouez15** [comment]
now i have this error
Traceback (most recent call last):
  File "C:\Users\faouez\Desktop\whapa-master\whapa-gui.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by FelipeCJSEP** [comment]
> now i have this error
> Traceback (most recent call last):
> File "C:\Users\faouez\Desktop\whapa-master\whapa-gui.py", line 4, in
> import requests
> ModuleNotFoundError: No module named 'requests'

run the commands: "pip install requests" and "pip install gpsoauth"

**Comment by B16f00t** [comment]
Read the installation procedure before opening issues.
Whagodri works with python version > 3.7.7

**Comment by wajid1975** [comment]
I have Python 3.8.5, Still i am getting  Error=BadAuthentication, does this really work, please help
