### ISSUE TITLE
[e] Error:  Requested entity was not found. [e] Unable to locate google drive file map for: com.whatsapp <Response [404]> [i] Error 'name'

### ISSUE THREAD

**Issue by michaelsibarani** [B16f00t/whapa#55]
always appear error like this
[e] Error:  Requested entity was not found. [e] Unable to locate google drive file map for: com.whatsapp <Response [404]> [i] Error 'name'

help me please. thanks before

**Comment by B16f00t** [comment]
Please, read first the closed issues.
#51 
And common issues.
