### ISSUE TITLE
type object 'ConfigParser' has no attribute 'NoSectionError'

### ISSUE THREAD

**Issue by alexynior28** [B16f00t/whapa#56]
Hey, thanks for the tool.

I get the following error when using the Drive tool. Can you help me?

![error](https://user-images.githubusercontent.com/19245743/83180738-7e98f900-a0e9-11ea-9156-973edfce0cb9.PNG)

`Traceback (most recent call last):
  File ".\libs\whagodri.py", line 57, in getConfigs
    passw = config.get('auth', 'passw')
  File "C:\Python38-32\lib\configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "C:\Python38-32\lib\configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "C:\Python38-32\lib\configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\libs\whagodri.py", line 266, in <module>
    getConfigs()
  File ".\libs\whagodri.py", line 65, in getConfigs
    except(ConfigParser.NoSectionError, ConfigParser.NoOptionError):
AttributeError: type object 'ConfigParser' has no attribute 'NoSectionError'`

**Comment by B16f00t** [comment]
You have settings.cfg file corrupt.

**Comment by alexynior28** [comment]
I have placed the data as the following image (they are not real on this screen)

![error](https://user-images.githubusercontent.com/19245743/83342492-b94f8c80-a2b5-11ea-8d20-9a8a65dd524d.PNG)

Could you please tell me if something's wrong?

**Comment by B16f00t** [comment]
Did you fix the issue with whagodri?

**Comment by alexynior28** [comment]
Hey, not yet.

I'll try to prove it with another Whatsapp account
