### ISSUE TITLE
  File "whapa-gui.py", line 1049, in <module>    File "whapa-gui.py", line 521, in __init__

### ISSUE THREAD

**Issue by tarjetasprof** [B16f00t/whapa#59]
Hello, I have Debian Buster 10 and this appearse when I try to execute. 

python3 whapa-gui.py
Traceback (most recent call last):
  File "whapa-gui.py", line 1049, in <module>
    Whapa(img_folder, icons)
  File "whapa-gui.py", line 521, in __init__
    update = (request.text.split('itemprop="about">')[1]).split("</span>")[0].strip("\n ")
IndexError: list index out of range

¿May you help me with that issue?
Thanks, 
Guille

**Comment by B16f00t** [comment]
Update to the latest version

**Comment by tarjetasprof** [comment]
Just done, thanks
