### ISSUE TITLE
Whagodri: [e] Unable to locate google drive file map for: com.whatsapp

### ISSUE THREAD

**Issue by tulblut** [B16f00t/whapa#6]
Hi
I'm trying to download a backup previously marked as "deactivated" on google drive. Launching whagodri -s automatically makes the backups "active" again on GD but I have this error ([e] Unable to locate google drive file map for: com.whatsapp) and can't download anything.
I've setted my settings.cfg with username, password, a devid of a android phone and the cellnumber in this form "390000000000" (with the real number and not the zeros obv). What can I do?

**Comment by B16f00t** [comment]
In Windows systems sometimes there are problems with the version of python, I recommend that you run it in linux or Linux virtual machine

**Comment by tulblut** [comment]
I tried with Python27 in both Windows 7 and Debian 9 "Stretch" with the same result. It seems that the program is working correctly but it can't find this "file map". (I'm not a programmer and I don't have any clue of google api inner workings). In google drive settings the backup is 325MB and it was last backupped in september 2016.

**Comment by B16f00t** [comment]
If the backup is disabled in Google Drive, it can not be recovered, you can try: python whagodri.py -i and see what backups are available to download.

**Comment by necromancer99999** [comment]
is there really no backup available ? 
I get this error too. It happen in same situation
After I delete manually my backup on google drive, then my whatsapp make backup itself and complete on google drive with same cell phone number.
It cant restore and get error 

`[e] Unable to locate google drive file map for: com.whatsapp`

But when i go to my google drive, there is whatsapp's backup available with new date

How to fix it ? I search on google, they ask to put cell phone number on setting. But my number is correct

thanks

**Comment by B16f00t** [comment]
that error occurs when the phone number is not properly configured, you
must put the country code followed by the number, without symbols. make
sure you do not have activated 2fa
