### ISSUE TITLE
Requested entity was not found

### ISSUE THREAD

**Issue by yakkobr** [B16f00t/whapa#62]
__      __.__             ________      ________        .__
    /  \    /  \  |__ _____   /  _____/  ____\______ \_______|__|
    \   \/\/   /  |  \\__  \ /   \  ___ /  _ \|    |  \_  __ \  |
     \        /|   Y  \/ __ \\    \_\  (  <_> )    `   \  | \/  |
      \__/\  / |___|  (____  /\______  /\____/_______  /__|  |__|
           \/       \/     \/        \/              \/

    -------------- Whatsapp Google Drive Extractor --------------
[i] Searching...

Your Google Access Token: ya29.morecode.... bla bla bla

[e] Error:  Requested entity was not found.
[e] Unable to locate google drive file map for: com.whatsapp <Response [404]>
[i] Error 'name'

![Screenshot_2020-08-18-17-11-10-327_com whatsapp](https://user-images.githubusercontent.com/14094950/90561132-9aef8380-e176-11ea-9c4b-8a4c473c6bc4.jpg)

**Comment by B16f00t** [comment]
Check the new version
