### ISSUE TITLE
Old backups cannot be decrypted

### ISSUE THREAD

**Issue by danzilberdan** [B16f00t/whapa#63]
whapa decrypts backups fine with the key from the same phone.
But when using old backups (from google drive), the same key fails to decrypt the database with the following error message:
"Error -3 while decompressing data: incorrect header check"

**Comment by B16f00t** [comment]
That is not a whapa problem, I understand that the decryption key for the new copies is different from that of the old copies

**Comment by danzilberdan** [comment]
But whatsApp is able to decrypt the old database. How does it do it if it's using a different key file?
My understanding is that each phone number has only one key file so the keys should be the same in the old and new phone.
