### ISSUE TITLE
Bad Authentication

### ISSUE THREAD

**Issue by alanpinheirolp** [B16f00t/whapa#64]
shows me bad authentication even the password is correct!

**Comment by B16f00t** [comment]
Which is you OS and python version?

**Comment by alanpinheirolp** [comment]
> Which is you OS and python version?
> […](#)
> Sent from my iPhone
> On 10 Sep 2020, at 18:25, alanpinheirolp ***@***.***> wrote: ﻿ shows me bad authentication even the password is correct! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.



Im using W10 x64 19041, python 3.7.1

**Comment by alanpinheirolp** [comment]
Im using W10 x64 19041, python 3.7.1

Atenciosamente,
Alan Pinheiro de Souza

________________________________
De: Ivan Moreno <notifications@github.com>
Enviado: quinta-feira, 10 de setembro de 2020 15:15
Para: B16f00t/whapa <whapa@noreply.github.com>
Cc: alanpinheirolp <alan_l_p@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [B16f00t/whapa] Bad Authentication (#64)


Which is you OS and python version?

**Comment by B16f00t** [comment]
Check the new version

**Comment by alanpinheirolp** [comment]
> Check the new version

thanks dude, problem solved
