### ISSUE TITLE
passwords with special characters are getting interpolated by configparser

### ISSUE THREAD

**Issue by RMHogervorst** [B16f00t/whapa#66]
The configparser does interpolation of values automatically and it messes up the process
when you have special characters.

A solution is to initialize the class with interpolation set to none, example whagodri.py line 55

```
def getConfigs():
    global gmail, passw, celnumbr
    config = ConfigParser(interpolation=None)
```

**Comment by B16f00t** [comment]
Thanks for the advice, I'll change it.
