### ISSUE TITLE
ImportError: cannot import name 'update'

### ISSUE THREAD

**Issue by reaktr4** [B16f00t/whapa#67]
OS: Windows 10
Python Version: 3.5.2

Successfully installed the packages from ```requirements.txt```.

Running ```C:\Python35\python.exe .\whapa-gui.py``` on PowerShell, gives me the following error:
```Traceback (most recent call last):
  File ".\whapa-gui.py", line 4, in <module>
    from libs import update
ImportError: cannot import name 'update'```

Any hints or solutions to solve this would be great!

**Comment by B16f00t** [comment]
You must change your python version >3.72

**Comment by reaktr4** [comment]
@B16f00t Thank you for your reply!
