### ISSUE TITLE
mergre

### ISSUE THREAD

**Issue by anoureldin** [B16f00t/whapa#68]
Hello 
i tried to merge two databases but i get 

     __      __.__                                               
    /  \    /  \  |__ _____    _____   ___________  ____   ____  
    \   \/\/   /  |  \\__  \  /     \_/ __ \_  __ \/ ___\_/ __ \ 
     \        /|   Y  \/ __ \|  Y Y  \  ___/|  | \/ /_/  >  ___/ 
      \__/\  / |___|  (____  /__|_|  /\___  >__|  \___  / \___  >
           \/       \/     \/      \/     \/     /_____/      \/ 
    ------------------- Whatsapp Merger v1.0 -----------------
    
[e] No databases to merge

i added two databases backup in one folder and i chosed this folder as path

**Comment by AboTyim** [comment]
Hello

No databases to merge
message error:
```
Traceback (most recent call last):
  File "./libs/whamerge.py", line 428, in <module>
    merge(args.path, args.output)
  File "./libs/whamerge.py", line 186, in merge
    elements_chatlist_cursor = cursor_read.execute("SELECT " + str_chatlist_cols + " FROM chat_list WHERE _id IN (" + str_id_chatlist_cols + ");")
sqlite3.OperationalError: no such column: deleted_message_id
```

**Comment by limsifu** [comment]
get this error

after type pip3 install -r /requirements.txt

C:\whapa-master\doc>pip3 install -r requirements.txt
Collecting pycryptodome
  Using cached pycryptodome-3.9.8.tar.gz (15.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\sflim\appdata\local\programs\python\python39-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sflim\\AppData\\Local\\Temp\\pip-install-1maw075y\\pycryptodome\\setup.py'"'"'; __file__='"'"'C:\\Users\\sflim\\AppData\\Local\\Temp\\pip-install-1maw075y\\pycryptodome\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\sflim\AppData\Local\Temp\pip-pip-egg-info-ivb3dxpd'
         cwd: C:\Users\sflim\AppData\Local\Temp\pip-install-1maw075y\pycryptodome\
    Complete output (20 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sflim\AppData\Local\Temp\pip-install-1maw075y\pycryptodome\setup.py", line 457, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\sflim\AppData\Local\Temp\pip-install-1maw075y\pycryptodome\compiler_opt.py", line 341, in set_compiler_options
        clang = compiler_is_clang()
      File "C:\Users\sflim\AppData\Local\Temp\pip-install-1maw075y\pycryptodome\compiler_opt.py", line 251, in compiler_is_clang
        return test_compilation(source, msg="clang")
      File "C:\Users\sflim\AppData\Local\Temp\pip-install-1maw075y\pycryptodome\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
      File "c:\users\sflim\appdata\local\programs\python\python39-32\lib\distutils\_msvccompiler.py", line 323, in compile
        self.initialize()
      File "c:\users\sflim\appdata\local\programs\python\python39-32\lib\distutils\_msvccompiler.py", line 220, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\sflim\appdata\local\programs\python\python39-32\lib\site-packages\setuptools\msvc.py", line 314, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "c:\users\sflim\appdata\local\programs\python\python39-32\lib\site-packages\setuptools\msvc.py", line 268, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    Testing support for clang
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by B16f00t** [comment]
> 
> 
> Hello
> i tried to merge two databases but i get
> 
> ```
>  __      __.__                                               
> /  \    /  \  |__ _____    _____   ___________  ____   ____  
> \   \/\/   /  |  \\__  \  /     \_/ __ \_  __ \/ ___\_/ __ \ 
>  \        /|   Y  \/ __ \|  Y Y  \  ___/|  | \/ /_/  >  ___/ 
>   \__/\  / |___|  (____  /__|_|  /\___  >__|  \___  / \___  >
>        \/       \/     \/      \/     \/     /_____/      \/ 
> ------------------- Whatsapp Merger v1.0 -----------------
> ```
> 
> [e] No databases to merge
> 
> i added two databases backup in one folder and i chosed this folder as path

the databases have to be unencrypted, in order to merge.

**Comment by B16f00t** [comment]
> 
> 
> Hello
> 
> No databases to merge
> message error:
> 
> ```
> Traceback (most recent call last):
>   File "./libs/whamerge.py", line 428, in <module>
>     merge(args.path, args.output)
>   File "./libs/whamerge.py", line 186, in merge
>     elements_chatlist_cursor = cursor_read.execute("SELECT " + str_chatlist_cols + " FROM chat_list WHERE _id IN (" + str_id_chatlist_cols + ");")
> sqlite3.OperationalError: no such column: deleted_message_id
> ```

If you are merging old databases, you probably don't have the deleted_message_id column.
You can add it with sqlitebrowser, or change the whamerge code a bit.
