### ISSUE TITLE
click on whapa-gui.bat

### ISSUE THREAD

**Issue by limsifu** [B16f00t/whapa#69]
Get Below error after type **whapa-gui.py** at command Prompt

Traceback (most recent call last):
  File "D:\whapa-master\whapa-gui.py", line 1060, in <module>
    if sys.platform == "win32" or sys.platform == "win64" or sys.platform == "cygwin":
NameError: name 'sys' is not defined

**Comment by yilmazca** [comment]
I solved this problem with this method. Please define OS static value in **whapa-gui.py** file.

Find
`if sys.platform == "win32" or sys.platform == "win64" or sys.platform == "cygwin":
            system = "Windows"
        else:
            system = "Linux"`

Change with this
`system = "Windows"`

Find
`system = ""`

Change your with OS type
`system = "Windows"`

and save it Voila!

**Comment by raghava2030** [comment]
i am also facing the same issue, tried defining static OS value as windows but still the same.

**Comment by limsifu** [comment]
At the end I just uninstall python 3.9 and install Python 3.7.5.
