### ISSUE TITLE
Traceback (most recent call last):   File "whapa-gui.py", line 1049, in <module>     Whapa(img_folder, icons)   File "whapa-gui.py", line 521, in __init__     update = (request.text.split('itemprop="about">')[1]).split("</span>")[0].strip("\n ") IndexError: list index out of range

### ISSUE THREAD

**Issue by joseruiloba** [B16f00t/whapa#71]
Hi guys:

Im receiving the following error:
Traceback (most recent call last):
  File "whapa-gui.py", line 1049, in <module>
    Whapa(img_folder, icons)
  File "whapa-gui.py", line 521, in __init__
    update = (request.text.split('itemprop="about">')[1]).split("</span>")[0].strip("\n ")
IndexError: list index out of range

I tried with the python version 3.7.9 (32 and 64 bits), believing that could be the python version 3.8.6 and 3.9.0 (32 and 64 as well) and in all the times I tried to run it, I got the same error. I believe 3 months ago I used the tool with the version 3.8.6 and works perfectly, now I not sure what I'm doing wrong, I will apreciate your support with this.

Verifiying previous issues apparently is the same problem from issues:
Issue with opening the program #58
Error when I try to open Whapa.py #57
File "whapa-gui.py", line 1049, in <module> File "whapa-gui.py", line 521, in __init__ #59

Thanks in Advance.

JR
![error](https://user-images.githubusercontent.com/10384984/96359274-97c13700-10d6-11eb-8cdf-8e2e5016cb7f.JPG)

**Comment by falisco** [comment]
Hi,

I had the same error but found the solution.

As the error says, in line 521, there is an error when checking the version. I think it's because the page https://github.com/B16f00t/whapa has changed and the text "itemprop="about">" doesn't exist now.

My solution is to comment these two lines (521 and 522) adding # at the beginning of each line, save the file and run it again with no problems:

        request = requests.get("https://github.com/B16f00t/whapa")
        #update = (request.text.split('itemprop="about">')[1]).split("</span>")[0].strip("\n ")
        #current_version = "{} v{}".format(title, version)"""
        #if update != current_version:
         #   messagebox.showinfo("Update", "New version available\n{}".format(update))
          #  webbrowser.open_new_tab("https://github.com/B16f00t/whapa")

Hope it helps

**Comment by joseruiloba** [comment]
You are the best... it runs right away after the update. I really appreciate it.

![whapa](https://user-images.githubusercontent.com/10384984/96879615-e0b01d00-1441-11eb-8ce2-7b4738d7781f.JPG)

**Comment by joseruiloba** [comment]
Works perfectly now... thanks for the support.

**Comment by joseruiloba** [comment]
I really appreciate the support, Falisco.

Great help dude, Thanks.

Regards,

J. Ruiloba

**Comment by falisco** [comment]
I'm glad it helped you.

**Comment by B16f00t** [comment]
Your problems are that you are using old versions of whapa, upgrade to the latest version.

**Comment by joseruiloba** [comment]
Actually I downloaded the last version for the Github repository, I don't
know if there any other link that guide you to a different version.

Regards,

J. R.

**Comment by B16f00t** [comment]
The picture show a old version. The latest version is 1.21
