### ISSUE TITLE
Error=BadAuthentication

### ISSUE THREAD

**Issue by limsifu** [B16f00t/whapa#72]
Requesting Auth for Google....
Failed

Error=BadAuthentication

   Workaround
-----------------
1. Check that your email and password are correct, if so change your google password and try again.
2. Your are using a old python version. Works > 3.7.7.
3. Update the gpsoauth dependency to its latest version, use in a terminal: 'pip install -U gpsoauth' or 'pip3 install -U gpsoauth'
settings.cfg
[report]
logo = ./cfg/logo.png
company =
record =
unit =
examiner =
notes =

[auth]
gmail = xxx@gmail.com
passw = xxx
celnumbr = xxx

User and Password is correct.

**Comment by B16f00t** [comment]
Are you using the latest version of whapa?

**Comment by faliagag** [comment]
It happens to me exactly the same.
I am with version whapa 1.21, phyton 3.7.7.
Update gpsoauth
And still I get Error = BadAuthentication

**Comment by inimaginablexhs** [comment]
i have the same problem :c

**Comment by molossusbook** [comment]
Hi: sounds like a great tool but cannot get it to work, because I get same problem with "**BadAuthentication**" 
Last version of whapa (updated today) and python, under lubuntu18.
Email and password checked and correct. Tried to change password but does not solve.
I wonder if there is anything I have to do on the Google side: any account setting? any unlocking?
visited https://accounts.google.com/DisplayUnlockCaptcha and unlocked access there.
Just let me know if you need me to produce other info to let you reproduce and/or understand the issue 
thanks a lot

**Comment by B16f00t** [comment]
There is a problem with the latest version of requests.
I recommend install requests 2.21 to solve it.

**Comment by inimaginablexhs** [comment]
install the request 2.21 and I continue with the problem :c

**Comment by sobelito** [comment]
I have seen an interesting behavior where it looks like these calls are failing w/ "BadAuthentication" if run from VMWare or from an EC2 instances, but they work from Windows Desktop and OSX. 

In looking at the ["Recent security activity"](https://myaccount.google.com/u/0/notifications?origin%3D3&origin=3) and clicking on the individual event, I can see "VMWare Virtual Platform" or "t3.medium" respectively on the failed attempts. Anyway, just wanted to share the data points.

I also tested from Windows Desktop but VPNing through an EC2 IP address, and this worked.

**Comment by sobelito** [comment]
> There is a problem with the latest version of requests. I recommend install requests 2.21 to solve it.
> […](#)
> Sent from my iPhone
> On 22 Nov 2020, at 22:23, inimaginablexhs ***@***.***> wrote: ﻿ i have the same problem :c — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you! Indeed, did "pip install requests==2.21.0" on the EC2 instance (as noted above) and it worked.

**Comment by molossusbook** [comment]
installed requests 2.21.0 and IT DID WORK for me, and that is the good news

just to make sure, here below is the output I get when checking a whatsapp backup
do you confirm this indicates an empty/corrupt backup? (that would be the bad part of the news)

thank you all for the support

**-------------- Whatsapp Google Drive Extractor --------------
[i] Searching...

Requesting Auth for Google....
Granted

Getting Token from Google....
Granted

No files for this backup**

**Comment by B16f00t** [comment]
It seems that the google drive account linked to the phone does not have any backup. So it may be a bad backup or one that never existed.

**Comment by suttter** [comment]
Problem solved after installing 2.21.0.

I got the msgstore.db.crypt12 file but the key is needed to decrypt it. Is it possible to get the msgstore.db file or the key?

**Comment by molossusbook** [comment]
ok. will also double check by creating another (valid) backup and trying with that
thanks!

**Comment by shamanasanka** [comment]
Hi,

I'm getting this error, what should i do?

File "E:\whapa-master\libs\whagodri.py", line 296, in
getConfigs()
File "E:\whapa-master\libs\whagodri.py", line 64, in getConfigs
except(ConfigParser.NoSectionError, ConfigParser.NoOptionError):
AttributeError: type object 'ConfigParser' has no attribute 'NoSectionError'

Thanks

**Comment by Samour50** [comment]
> Are you using the latest version of whapa?

Yes
