### ISSUE TITLE
How to manually find Google token?

### ISSUE THREAD

**Issue by atlx** [B16f00t/whapa#74]
Hi, I'm trying to figure out how to find the Google token (Google Account token) without providing auth (already logged in on the browser).

Which request contains the token? Or is it on the cookies?

**Comment by B16f00t** [comment]
Whapagodri does not store the token, but uses it in the request within the header.

    header = {'Authorization': 'Bearer ' + bearer, 'User-Agent': 'WhatsApp/2.19.244 Android/9.0 Device/Whapa'}
    url_data = "https://backup.googleapis.com/v1/clients/wa/backups/{}".format(celnumbr)
    request_data = requests.get(url_data, headers=header)

**Comment by dev-point-team** [comment]
create oauth authorization from google console, it will be like

https://accounts.google.com/o/oauth2/v2/auth?client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT&response_type=code&scope=https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/drive.file
