### ISSUE TITLE
Config parser error

### ISSUE THREAD

**Issue by shamanasanka** [B16f00t/whapa#76]
Hi,

I'm getting this error, what should i do?

File "E:\whapa-master\libs\whagodri.py", line 296, in <module>
    getConfigs()
  File "E:\whapa-master\libs\whagodri.py", line 64, in getConfigs
    except(ConfigParser.NoSectionError, ConfigParser.NoOptionError):
AttributeError: type object 'ConfigParser' has no attribute 'NoSectionError'

Thanks

**Comment by B16f00t** [comment]
What is your OS and python version?

**Comment by B16f00t** [comment]
This is not a Whapa mistake
