### ISSUE TITLE
Problem with Whacipher encryption

### ISSUE THREAD

**Issue by Artoriona** [B16f00t/whapa#77]
Hi,
I have been unable to restore a crypt12 file created with Whacipher. WhatsApp can see it but can't restore it. There seems to be a difference in size between the original crypt12 file and the new crypt12 file (some kbytes smaller) even when the database is the same.

**Comment by B16f00t** [comment]
What OS are you using? let me check it.

**Comment by Artoriona** [comment]
I am on Windows 10.

**Comment by B16f00t** [comment]
I've been testing and I don't see the problem with encrypting backups.
