### ISSUE TITLE
Requirements.txt improvements

### ISSUE THREAD

**Issue by Samour50** [B16f00t/whapa#78]
ERROR: Could not find a version that satisfies the requirement sys (from -r ./doc/requirements.txt (line 6)) (from versions: none)
ERROR: No matching distribution found for sys (from -r ./doc/requirements.txt (line 6))

C:\whapa-master>python whapa-gui.py
Traceback (most recent call last):
  File "whapa-gui.py", line 5, in <module>
    from libs import update
  File "C:\whapa-master\libs\update.py", line 1, in <module>
    ﻿import requests
ModuleNotFoundError: No module named 'requests'

pip3 install requests is also required before UI launches.

Consider including requests in the requirement and fixing or removing sys.

Also consider https://github.com/B16f00t/whapa/issues/72 to use a specific version of requests

**Comment by Samour50** [comment]
Forgot to add this one

Traceback (most recent call last):
  File ".\libs\whagodri.py", line 1, in <module>
    from gpsoauth import google
ModuleNotFoundError: No module named 'gpsoauth'

**Comment by Samour50** [comment]
So gpsoautho and requests (2.21.0 specifically) are missing, and sys seems to not even be required

After installing these it runs fine

**Comment by B16f00t** [comment]
I have modified requirements.txt and I have deleted the sys line.
