### ISSUE TITLE
Merge error

### ISSUE THREAD

**Issue by mk148a** [B16f00t/whapa#79]
[+] Created C:\whatsapp\whapa-master\msgstore_merge.db
[+] Merging: msgstore.db
   [-] C:\whatsapp\whapa-master\msgstore_merge.db --> 4128 messages, 57 chats, 129 replies, 272 thumbnails
   [-] msgstore.db --> 298791 messages, 471 chats, 12851 replies, 20984 thumbnails
[+] Looking for new messages
   [-] New messages 296706
[+] Looking for new chats
   [-] New chats 423
[+] Looking for new replies
   [-] New replies 12801
[+] Looking for new Thumbnails
   [-] New Thumbnails 20898
Traceback (most recent call last):
  File ".\libs\whamerge.py", line 428, in <module>
    merge(args.path, args.output)
  File ".\libs\whamerge.py", line 186, in merge
    **elements_chatlist_cursor = cursor_read.execute("SELECT " + str_chatlist_cols + " FROM chat_list WHERE _id IN (" + str_id_chatlist_cols + ");")
sqlite3.OperationalError: no such column: deleted_message_id**

**Comment by B16f00t** [comment]
#68
