### ISSUE TITLE
Can you do a complete export of WhatsApp Data?

### ISSUE THREAD

**Issue by expelledboy** [B16f00t/whapa#82]
I am looking to do a guide to export data, which will be at a later point able to be imported in Signal, and push it via social media.

Can this be done with WHAGODRI? I wish for a copy of all messages across private and group chat with metadata about the contact, images and videos.

**Comment by B16f00t** [comment]
Whagodri is only good for downloading your medias and encrypted chats.

**Comment by expelledboy** [comment]
Are you saying the export is limited? Is media and chat not everything? How do I get started?

**Comment by B16f00t** [comment]
With whagodri you can get your multimedia files, but for chats it is more difficult because if you don't have the private key you can't decrypt the information.

**Comment by B16f00t** [comment]
In a few days I'll release a new tool for export chats to html.

**Comment by B16f00t** [comment]
New version 1.40 include the tool whachat to parse exported chats.
