### ISSUE TITLE
Error=NeedsBrowser if i use real password (no password app)

### ISSUE THREAD

**Issue by Oshawott-kun** [B16f00t/whapa#84]
hey man 
i got issue about... why i cant use real password. if i use real password. error say (Error=NeedsBrowser)
i done type password on browser but still not work 
can you fix this

(Yeah i tried use passwordapp and is work but i so lazy make password app again hehe)

**Comment by B16f00t** [comment]
If you use 2FA, password app is the only method and if you want to use clear password you have to disable it.

**Comment by Oshawott-kun** [comment]
I've disabled everything but still can't

**Comment by B16f00t** [comment]
What's your problem?

**Comment by Oshawott-kun** [comment]
oh wait is work now 
i close this issue
