### ISSUE TITLE
Issue with whacipher during decryption

### ISSUE THREAD

**Issue by manthanf1** [B16f00t/whapa#86]
OS: Linux
Python: 3.8.5

Ran python3 whapa-gui.py and got an error. Fixed with
`pip3 install pycryptodome` and replaced `from Crypto.Cipher import AES` to `from Cryptodome.Cipher import AES` in libs/whacipher.py 
 
After loading crypt12 db and key in GUI, during decryption I get the following error: 
[i] Starting to decrypt...
[e] An error has ocurred decrypting '/media/veracrypt1/msgstore.db.crypt12' -  Error -3 while decompressing data: invalid code lengths set

**Comment by B16f00t** [comment]
I don't understand why you modify the code. Use the version with the specified libraries.
You only have to install the requirements: pip3 install -r ./doc/requirements.txt

**Comment by manthanf1** [comment]
Receiving the same error without any changes in scripts and having installed all required packages
```

[i] Starting to decrypt...
[e] An error has ocurred decrypting '/media/veracrypt1/Takeout/WHATSAPP/895msgstore.db.crypt12' -  Error -3 while decompressing data: invalid code lengths set
```

Key is from /data/data/com.whatsapp/files/

**Comment by manthanf1** [comment]
Receiving the same error without any changes in scripts and having installed all required packages


```
[i] Starting to decrypt...
[e] An error has ocurred decrypting '/media/veracrypt1/msgstore.db.crypt12' -  Error -3 while decompressing data: invalid code lengths set
```

Key is from /data/data/com.whatsapp/files/

**Comment by B16f00t** [comment]
Ok, I'll check it

**Comment by B16f00t** [comment]
Give a try the new version, if you continue to have problems, the key is not valid for that backup.
