### ISSUE TITLE
Bad Authentication Error for Google Drive

### ISSUE THREAD

**Issue by sulzeb** [B16f00t/whapa#88]
Error: BadAuthentication 

Getting this error for Whagodri all credentials are correct. Any fix for this please?

**Comment by sulzeb** [comment]
@B16f00t 
Can you pls help

**Comment by B16f00t** [comment]
#72 Don't open the same issue, and read the one closed.
you only have to change the request version. 
pip install --upgrade -r ./doc/requirements.txt
