### ISSUE TITLE
Images not mapped correctly in the HTML report

### ISSUE THREAD

**Issue by aw-infosec** [B16f00t/whapa#89]
OS: Windows 10
Python Version: 3.9.1

I found that images and other resources are not correctly mapped in the HTML report.
For example, when I clicked on an image, it went the following path:
`file:///C:/whapa-master/report/.C:/whapa-master/report/Media/WhatsApp%20Images/IMG-20000101-WA0001.jpg`

However, the correct path should be:
`file:///C:/whapa-master/report/Media/WhatsApp%20Images/IMG-20000101-WA0001.jpg`

Any advise or solution to fix this issue?

I also got the following error when I click the "status" option.
_NameError: name 'local' is not defined_
```
wa.db connected
msgstore.db connected

Status
Loading data ...
Number of messages: 0
Traceback (most recent call last):
  File "C:\whapa-master\libs\whapa.py", line 2050, in <module>
    info(args.info)
  File "C:\whapa-master\libs\whapa.py", line 1620, in info
    messages(sql_consult, result[0], report_html, local)
NameError: name 'local' is not defined
```

**Comment by B16f00t** [comment]
Ok, let me check it but it's easy to solve.

**Comment by Aminu0234** [comment]
Nice

**Comment by B16f00t** [comment]
New version 1.40 fix the issue. Thanks

**Comment by nadavcoh** [comment]
Hi! Great project, thank you for all the work you put into this.
This bug is not resolved in current master, href now point to ".g"
I was able to circumvent by reverting to 1.3 and removing all instances of ".C:/whapa-master/report/" by batch find & replace (Notepad++)

**Comment by B16f00t** [comment]
Pls. give a try the new version 1.43
