### ISSUE TITLE
OSX TK inter problem solved

### ISSUE THREAD

**Issue by FetchFast** [B16f00t/whapa#92]
Please add this to the FAQ/Instructions:

To get this working on OSX:

1) install a later version of TK 
`brew install tcl-tk`
2) Uninstall python3 and then download and reinstall python from python.org
`brew uninstall python3`
3) Run with 
`python3.9  whapa-gui.py`

This is how you fix the error on OSX:
```
% python3 whapa-gui.py                             
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "whapa-gui.py", line 1457, in <module>
    Whapa(img_folder, icons)
  File "whapa-gui.py", line 56, in __init__
    self.iconlogo = PhotoImage(file=self.icons[0])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 4061, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 4006, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "/Users/j/src/whapa/images/logo.png"
```

References:
https://gist.github.com/haliaeetus/529ac14438d139ee905101b99224d9b3
https://gist.github.com/txoof/675e72d43f1bfbade04fdcec99ff4085
https://stackoverflow.com/questions/36760839/why-my-python-installed-via-home-brew-not-include-tkinter/48737927
https://github.com/pyenv/pyenv/issues/94

**Comment by FetchFast** [comment]
I also needed to:
`pip3 install pycryptodome`
as well but I'm not sure where this would go in the install instructions

**Comment by B16f00t** [comment]
Thank you so much for your contribution
